/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocatePartyResponse {
    #[serde(rename = "partyDetails", skip_serializing_if = "Option::is_none")]
    pub party_details: Option<Box<models::PartyDetails>>,
}

impl AllocatePartyResponse {
    pub fn new() -> AllocatePartyResponse {
        AllocatePartyResponse {
            party_details: None,
        }
    }
}

