/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocateExternalPartyRequest : Required authorization:   ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id) OR IsAuthenticatedUser(user_id)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocateExternalPartyRequest {
    /// TODO(#27670) support synchronizer aliases Synchronizer ID on which to onboard the party  Required
    #[serde(rename = "synchronizer")]
    pub synchronizer: String,
    /// TopologyTransactions to onboard the external party Can contain: - A namespace for the party. This can be either a single NamespaceDelegation, or DecentralizedNamespaceDefinition along with its authorized namespace owners in the form of NamespaceDelegations. May be provided, if so it must be fully authorized by the signatures in this request combined with the existing topology state. - A PartyToParticipant to register the hosting relationship of the party, and the party's signing keys and threshold. Must be provided.  Required: must be non-empty
    #[serde(rename = "onboardingTransactions")]
    pub onboarding_transactions: Vec<models::SignedTransaction>,
    /// Optional signatures of the combined hash of all onboarding_transactions This may be used instead of providing signatures on each individual transaction  Optional: can be empty
    #[serde(rename = "multiHashSignatures", skip_serializing_if = "Option::is_none")]
    pub multi_hash_signatures: Option<Vec<models::Signature>>,
    /// The id of the ``Identity Provider`` If not set, assume the party is managed by the default identity provider.  Optional
    #[serde(rename = "identityProviderId", skip_serializing_if = "Option::is_none")]
    pub identity_provider_id: Option<String>,
    /// When true, this RPC will attempt to wait for the party to be allocated on the synchronizer before returning. When false, the allocation will happen asynchronously. This is a best effort only as this synchronization is only possible for non decentralized parties (single hosting node). For decentralized parties, this flag is ignored. Defaults to true.  Optional
    #[serde(rename = "waitForAllocation", skip_serializing_if = "Option::is_none")]
    pub wait_for_allocation: Option<bool>,
    /// The user who will get the act_as rights to the newly allocated party. If set to an empty string (the default), no user will get rights to the party.  Optional
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
}

impl AllocateExternalPartyRequest {
    /// Required authorization:   ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id) OR IsAuthenticatedUser(user_id)``
    pub fn new(synchronizer: String, onboarding_transactions: Vec<models::SignedTransaction>) -> AllocateExternalPartyRequest {
        AllocateExternalPartyRequest {
            synchronizer,
            onboarding_transactions,
            multi_hash_signatures: None,
            identity_provider_id: None,
            wait_for_allocation: None,
            user_id: None,
        }
    }
}

