/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllocateExternalPartyRequest : Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllocateExternalPartyRequest {
    /// TODO(#27670) support synchronizer aliases Synchronizer ID on which to onboard the party  Required
    #[serde(rename = "synchronizer")]
    pub synchronizer: String,
    /// TopologyTransactions to onboard the external party Can contain: - A namespace for the party. This can be either a single NamespaceDelegation, or DecentralizedNamespaceDefinition along with its authorized namespace owners in the form of NamespaceDelegations. May be provided, if so it must be fully authorized by the signatures in this request combined with the existing topology state. - A PartyToKeyMapping to register the party's signing keys. May be provided, if so it must be fully authorized by the signatures in this request combined with the existing topology state. - A PartyToParticipant to register the hosting relationship of the party. Must be provided.  Required: must be non-empty
    #[serde(rename = "onboardingTransactions")]
    pub onboarding_transactions: Vec<models::SignedTransaction>,
    /// Optional signatures of the combined hash of all onboarding_transactions This may be used instead of providing signatures on each individual transaction  Optional: can be empty
    #[serde(rename = "multiHashSignatures", skip_serializing_if = "Option::is_none")]
    pub multi_hash_signatures: Option<Vec<models::Signature>>,
    /// The id of the ``Identity Provider`` If not set, assume the party is managed by the default identity provider.  Optional
    #[serde(rename = "identityProviderId", skip_serializing_if = "Option::is_none")]
    pub identity_provider_id: Option<String>,
}

impl AllocateExternalPartyRequest {
    /// Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
    pub fn new(synchronizer: String, onboarding_transactions: Vec<models::SignedTransaction>) -> AllocateExternalPartyRequest {
        AllocateExternalPartyRequest {
            synchronizer,
            onboarding_transactions,
            multi_hash_signatures: None,
            identity_provider_id: None,
        }
    }
}

