/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssignCommand1 : Assign a contract
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignCommand1 {
    /// The ID from the unassigned event to be completed by this assignment. Must be a valid LedgerString (as described in ``value.proto``).  Required
    #[serde(rename = "reassignmentId")]
    pub reassignment_id: String,
    /// The ID of the source synchronizer Must be a valid synchronizer id  Required
    #[serde(rename = "source")]
    pub source: String,
    /// The ID of the target synchronizer Must be a valid synchronizer id  Required
    #[serde(rename = "target")]
    pub target: String,
}

impl AssignCommand1 {
    /// Assign a contract
    pub fn new(reassignment_id: String, source: String, target: String) -> AssignCommand1 {
        AssignCommand1 {
            reassignment_id,
            source,
            target,
        }
    }
}

