/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AssignCommand : Assign a contract
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AssignCommand {
    #[serde(rename = "value")]
    pub value: Box<models::AssignCommand1>,
}

impl AssignCommand {
    /// Assign a contract
    pub fn new(value: models::AssignCommand1) -> AssignCommand {
        AssignCommand {
            value: Box::new(value),
        }
    }
}

