/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanReadAs {
    #[serde(rename = "value")]
    pub value: Box<models::CanReadAs1>,
}

impl CanReadAs {
    pub fn new(value: models::CanReadAs1) -> CanReadAs {
        CanReadAs {
            value: Box::new(value),
        }
    }
}

