/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CanExecuteAsAnyParty : The rights of a user to prepare and execute transactions as any party. Its utility is predominantly for users that perform interactive submissions on behalf of many parties.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CanExecuteAsAnyParty {
    /// The rights of a user to prepare and execute transactions as any party. Its utility is predominantly for users that perform interactive submissions on behalf of many parties.
    #[serde(rename = "value")]
    pub value: serde_json::Value,
}

impl CanExecuteAsAnyParty {
    /// The rights of a user to prepare and execute transactions as any party. Its utility is predominantly for users that perform interactive submissions on behalf of many parties.
    pub fn new(value: serde_json::Value) -> CanExecuteAsAnyParty {
        CanExecuteAsAnyParty {
            value,
        }
    }
}

