/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Command1 : A command can either create a new contract or exercise a choice on an existing contract.
/// A command can either create a new contract or exercise a choice on an existing contract.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Command1 {
    Command1OneOf(Box<models::Command1OneOf>),
    Command1OneOf1(Box<models::Command1OneOf1>),
    Command1OneOf2(Box<models::Command1OneOf2>),
}

impl Default for Command1 {
    fn default() -> Self {
        Self::Command1OneOf(Default::default())
    }
}

