/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Command : A command can either create a new contract or exercise a choice on an existing contract.
/// A command can either create a new contract or exercise a choice on an existing contract.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Command {
    CommandOneOf(Box<models::CommandOneOf>),
    CommandOneOf1(Box<models::CommandOneOf1>),
    CommandOneOf2(Box<models::CommandOneOf2>),
    CommandOneOf3(Box<models::CommandOneOf3>),
}

impl Default for Command {
    fn default() -> Self {
        Self::CommandOneOf(Default::default())
    }
}

