/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Command1OneOf2 {
    #[serde(rename = "UnassignCommand")]
    pub unassign_command: Box<models::UnassignCommand>,
}

impl Command1OneOf2 {
    pub fn new(unassign_command: models::UnassignCommand) -> Command1OneOf2 {
        Command1OneOf2 {
            unassign_command: Box::new(unassign_command),
        }
    }
}

