/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandOneOf {
    #[serde(rename = "CreateAndExerciseCommand")]
    pub create_and_exercise_command: Box<models::CreateAndExerciseCommand>,
}

impl CommandOneOf {
    pub fn new(create_and_exercise_command: models::CreateAndExerciseCommand) -> CommandOneOf {
        CommandOneOf {
            create_and_exercise_command: Box::new(create_and_exercise_command),
        }
    }
}

