/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandOneOf3 {
    #[serde(rename = "ExerciseCommand")]
    pub exercise_command: Box<models::ExerciseCommand>,
}

impl CommandOneOf3 {
    pub fn new(exercise_command: models::ExerciseCommand) -> CommandOneOf3 {
        CommandOneOf3 {
            exercise_command: Box::new(exercise_command),
        }
    }
}

