/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CommandOneOf1 {
    #[serde(rename = "CreateCommand")]
    pub create_command: Box<models::CreateCommand>,
}

impl CommandOneOf1 {
    pub fn new(create_command: models::CreateCommand) -> CommandOneOf1 {
        CommandOneOf1 {
            create_command: Box::new(create_command),
        }
    }
}

