/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionResponseOneOf2 {
    #[serde(rename = "OffsetCheckpoint")]
    pub offset_checkpoint: Box<models::OffsetCheckpoint>,
}

impl CompletionResponseOneOf2 {
    pub fn new(offset_checkpoint: models::OffsetCheckpoint) -> CompletionResponseOneOf2 {
        CompletionResponseOneOf2 {
            offset_checkpoint: Box::new(offset_checkpoint),
        }
    }
}

