/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionStreamResponse {
    #[serde(rename = "completionResponse")]
    pub completion_response: Box<models::CompletionResponse>,
}

impl CompletionStreamResponse {
    pub fn new(completion_response: models::CompletionResponse) -> CompletionStreamResponse {
        CompletionStreamResponse {
            completion_response: Box::new(completion_response),
        }
    }
}

