/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionStreamRequest {
    /// Only completions of commands submitted with the same user_id will be visible in the stream. Must be a valid UserIdString (as described in ``value.proto``).  Required unless authentication is used with a user token. In that case, the token's user-id will be used for the request's user_id.  Optional
    #[serde(rename = "userId", skip_serializing_if = "Option::is_none")]
    pub user_id: Option<String>,
    /// Non-empty list of parties whose data should be included. The stream shows only completions of commands for which at least one of the ``act_as`` parties is in the given set of parties. Must be a valid PartyIdString (as described in ``value.proto``).  Required: must be non-empty
    #[serde(rename = "parties")]
    pub parties: Vec<String>,
    /// This optional field indicates the minimum offset for completions. This can be used to resume an earlier completion stream. If not set the ledger uses the ledger begin offset instead. If specified, it must be a valid absolute offset (positive integer) or zero (ledger begin offset). If the ledger has been pruned, this parameter must be specified and greater than the pruning offset.  Optional
    #[serde(rename = "beginExclusive", skip_serializing_if = "Option::is_none")]
    pub begin_exclusive: Option<i64>,
}

impl CompletionStreamRequest {
    pub fn new(parties: Vec<String>) -> CompletionStreamRequest {
        CompletionStreamRequest {
            user_id: None,
            parties,
            begin_exclusive: None,
        }
    }
}

