/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionResponseOneOf1 {
    #[serde(rename = "Empty")]
    pub empty: serde_json::Value,
}

impl CompletionResponseOneOf1 {
    pub fn new(empty: serde_json::Value) -> CompletionResponseOneOf1 {
        CompletionResponseOneOf1 {
            empty,
        }
    }
}

