/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CompletionResponseOneOf {
    #[serde(rename = "Completion")]
    pub completion: Box<models::Completion>,
}

impl CompletionResponseOneOf {
    pub fn new(completion: models::Completion) -> CompletionResponseOneOf {
        CompletionResponseOneOf {
            completion: Box::new(completion),
        }
    }
}

