/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ConnectedSynchronizer {
    #[serde(rename = "synchronizerAlias")]
    pub synchronizer_alias: String,
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    #[serde(rename = "permission")]
    pub permission: Permission,
}

impl ConnectedSynchronizer {
    pub fn new(synchronizer_alias: String, synchronizer_id: String, permission: Permission) -> ConnectedSynchronizer {
        ConnectedSynchronizer {
            synchronizer_alias,
            synchronizer_id,
            permission,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Permission {
    #[serde(rename = "PARTICIPANT_PERMISSION_UNSPECIFIED")]
    ParticipantPermissionUnspecified,
    #[serde(rename = "PARTICIPANT_PERMISSION_SUBMISSION")]
    ParticipantPermissionSubmission,
    #[serde(rename = "PARTICIPANT_PERMISSION_CONFIRMATION")]
    ParticipantPermissionConfirmation,
    #[serde(rename = "PARTICIPANT_PERMISSION_OBSERVATION")]
    ParticipantPermissionObservation,
}

impl Default for Permission {
    fn default() -> Permission {
        Self::ParticipantPermissionUnspecified
    }
}

