/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreatedEvent : Records that a contract has been created, and choices may now be exercised on it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreatedEvent {
    /// The offset of origin, which has contextual meaning, please see description at messages that include a CreatedEvent. Offsets are managed by the participant nodes. Transactions can thus NOT be assumed to have the same offsets on different participant nodes. Required, it is a valid absolute offset (positive integer)
    #[serde(rename = "offset")]
    pub offset: i64,
    /// The position of this event in the originating transaction or reassignment. The origin has contextual meaning, please see description at messages that include a CreatedEvent. Node IDs are not necessarily equal across participants, as these may see different projections/parts of transactions. Required, must be valid node ID (non-negative integer)
    #[serde(rename = "nodeId")]
    pub node_id: i32,
    /// The ID of the created contract. Must be a valid LedgerString (as described in ``value.proto``). Required
    #[serde(rename = "contractId")]
    pub contract_id: String,
    /// The template of the created contract. The identifier uses the package-id reference format.  Required
    #[serde(rename = "templateId")]
    pub template_id: String,
    /// The key of the created contract. This will be set if and only if ``create_arguments`` is set and ``template_id`` defines a contract key. Optional
    #[serde(rename = "contractKey", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub contract_key: Option<Option<serde_json::Value>>,
    #[serde(rename = "createArgument", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub create_argument: Option<Option<serde_json::Value>>,
    /// Opaque representation of contract create event payload intended for forwarding to an API server as a contract disclosed as part of a command submission. Optional
    #[serde(rename = "createdEventBlob")]
    pub created_event_blob: String,
    /// Interface views specified in the transaction filter. Includes an ``InterfaceView`` for each interface for which there is a ``InterfaceFilter`` with  - its party in the ``witness_parties`` of this event, - and which is implemented by the template of this event, - and which has ``include_interface_view`` set.  Optional
    #[serde(rename = "interfaceViews", skip_serializing_if = "Option::is_none")]
    pub interface_views: Option<Vec<models::JsInterfaceView>>,
    /// The parties that are notified of this event. When a ``CreatedEvent`` is returned as part of a transaction tree or ledger-effects transaction, this will include all the parties specified in the ``TransactionFilter`` that are informees of the event. If served as part of a ACS delta transaction those will be limited to all parties specified in the ``TransactionFilter`` that are stakeholders of the contract (i.e. either signatories or observers). If the ``CreatedEvent`` is returned as part of an AssignedEvent, ActiveContract or IncompleteUnassigned (so the event is related to an assignment or unassignment): this will include all parties of the ``TransactionFilter`` that are stakeholders of the contract.  The behavior of reading create events visible to parties not hosted on the participant node serving the Ledger API is undefined. Concretely, there is neither a guarantee that the participant node will serve all their create events on the ACS stream, nor is there a guarantee that matching archive events are delivered for such create events.  For most clients this is not a problem, as they only read events for parties that are hosted on the participant node. If you need to read events for parties that may not be hosted at all times on the participant node, subscribe to the ``TopologyEvent``s for that party by setting a corresponding ``UpdateFormat``.  Using these events, query the ACS as-of an offset where the party is hosted on the participant node, and ignore create events at offsets where the party is not hosted on the participant node. Required
    #[serde(rename = "witnessParties", skip_serializing_if = "Option::is_none")]
    pub witness_parties: Option<Vec<String>>,
    /// The signatories for this contract as specified by the template. Required
    #[serde(rename = "signatories", skip_serializing_if = "Option::is_none")]
    pub signatories: Option<Vec<String>>,
    /// The observers for this contract as specified explicitly by the template or implicitly as choice controllers. This field never contains parties that are signatories. Required
    #[serde(rename = "observers", skip_serializing_if = "Option::is_none")]
    pub observers: Option<Vec<String>>,
    /// Ledger effective time of the transaction that created the contract. Required
    #[serde(rename = "createdAt")]
    pub created_at: String,
    /// The package name of the created contract. Required
    #[serde(rename = "packageName")]
    pub package_name: String,
}

impl CreatedEvent {
    /// Records that a contract has been created, and choices may now be exercised on it.
    pub fn new(offset: i64, node_id: i32, contract_id: String, template_id: String, created_event_blob: String, created_at: String, package_name: String) -> CreatedEvent {
        CreatedEvent {
            offset,
            node_id,
            contract_id,
            template_id,
            contract_key: None,
            create_argument: None,
            created_event_blob,
            interface_views: None,
            witness_parties: None,
            signatories: None,
            observers: None,
            created_at,
            package_name,
        }
    }
}

