/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateCommand : Create a new contract instance based on a template.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateCommand {
    /// The template of contract the client wants to create. Both package-name and package-id reference identifier formats for the template-id are supported. Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.  Required
    #[serde(rename = "templateId")]
    pub template_id: String,
    /// The arguments required for creating a contract from this template.  Required
    #[serde(rename = "createArguments", deserialize_with = "Option::deserialize")]
    pub create_arguments: Option<serde_json::Value>,
}

impl CreateCommand {
    /// Create a new contract instance based on a template.
    pub fn new(template_id: String, create_arguments: Option<serde_json::Value>) -> CreateCommand {
        CreateCommand {
            template_id,
            create_arguments,
        }
    }
}

