/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CreateUserRequest :  RPC requests and responses ///////////////////////////  Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(user.identity_provider_id)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CreateUserRequest {
    #[serde(rename = "user")]
    pub user: Box<models::User>,
    /// The rights to be assigned to the user upon creation, which SHOULD include appropriate rights for the ``user.primary_party``.  Optional: can be empty
    #[serde(rename = "rights", skip_serializing_if = "Option::is_none")]
    pub rights: Option<Vec<models::Right>>,
}

impl CreateUserRequest {
    ///  RPC requests and responses ///////////////////////////  Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(user.identity_provider_id)``
    pub fn new(user: models::User) -> CreateUserRequest {
        CreateUserRequest {
            user: Box::new(user),
            rights: None,
        }
    }
}

