/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeduplicationPeriodOneOf {
    #[serde(rename = "DeduplicationDuration")]
    pub deduplication_duration: Box<models::DeduplicationDuration>,
}

impl DeduplicationPeriodOneOf {
    pub fn new(deduplication_duration: models::DeduplicationDuration) -> DeduplicationPeriodOneOf {
        DeduplicationPeriodOneOf {
            deduplication_duration: Box::new(deduplication_duration),
        }
    }
}

