/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeduplicationPeriod : Specifies the deduplication period for the change ID. If omitted, the participant will assume the configured maximum deduplication time.  Optional
/// Specifies the deduplication period for the change ID. If omitted, the participant will assume the configured maximum deduplication time.  Optional
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeduplicationPeriod {
    DeduplicationPeriodOneOf(Box<models::DeduplicationPeriodOneOf>),
    DeduplicationPeriodOneOf1(Box<models::DeduplicationPeriodOneOf1>),
    DeduplicationPeriodOneOf2(Box<models::DeduplicationPeriodOneOf2>),
}

impl Default for DeduplicationPeriod {
    fn default() -> Self {
        Self::DeduplicationPeriodOneOf(Default::default())
    }
}

