/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DeduplicationPeriod1 : The actual deduplication window used for the submission, which is derived from ``Commands.deduplication_period``. The ledger may convert the deduplication period into other descriptions and extend the period in implementation-specified ways.  Used to audit the deduplication guarantee described in ``commands.proto``.  The deduplication guarantee applies even if the completion omits this field.  Optional
/// The actual deduplication window used for the submission, which is derived from ``Commands.deduplication_period``. The ledger may convert the deduplication period into other descriptions and extend the period in implementation-specified ways.  Used to audit the deduplication guarantee described in ``commands.proto``.  The deduplication guarantee applies even if the completion omits this field.  Optional
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum DeduplicationPeriod1 {
    DeduplicationPeriod1OneOf(Box<models::DeduplicationPeriod1OneOf>),
    DeduplicationPeriod1OneOf1(Box<models::DeduplicationPeriod1OneOf1>),
    DeduplicationPeriod1OneOf2(Box<models::DeduplicationPeriod1OneOf2>),
}

impl Default for DeduplicationPeriod1 {
    fn default() -> Self {
        Self::DeduplicationPeriod1OneOf(Default::default())
    }
}

