/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeduplicationOffset2 {
    #[serde(rename = "value")]
    pub value: i64,
}

impl DeduplicationOffset2 {
    pub fn new(value: i64) -> DeduplicationOffset2 {
        DeduplicationOffset2 {
            value,
        }
    }
}

