/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct DeduplicationPeriod2OneOf {
    #[serde(rename = "DeduplicationDuration")]
    pub deduplication_duration: Box<models::DeduplicationDuration2>,
}

impl DeduplicationPeriod2OneOf {
    pub fn new(deduplication_duration: models::DeduplicationDuration2) -> DeduplicationPeriod2OneOf {
        DeduplicationPeriod2OneOf {
            deduplication_duration: Box::new(deduplication_duration),
        }
    }
}

