/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Duration {
    #[serde(rename = "seconds")]
    pub seconds: i64,
    #[serde(rename = "nanos")]
    pub nanos: i32,
    /// This field is automatically added as part of protobuf to json mapping
    #[serde(rename = "unknownFields", skip_serializing_if = "Option::is_none")]
    pub unknown_fields: Option<String>,
}

impl Duration {
    pub fn new(seconds: i64, nanos: i32) -> Duration {
        Duration {
            seconds,
            nanos,
            unknown_fields: None,
        }
    }
}

