/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Event1 : Events in transactions can have two primary shapes:  - ACS delta: events can be CreatedEvent or ArchivedEvent - ledger effects: events can be CreatedEvent or ExercisedEvent  In the update service the events are restricted to the events visible for the parties specified in the transaction filter. Each event message type below contains a ``witness_parties`` field which indicates the subset of the requested parties that can see the event in question.
/// Events in transactions can have two primary shapes:  - ACS delta: events can be CreatedEvent or ArchivedEvent - ledger effects: events can be CreatedEvent or ExercisedEvent  In the update service the events are restricted to the events visible for the parties specified in the transaction filter. Each event message type below contains a ``witness_parties`` field which indicates the subset of the requested parties that can see the event in question.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum Event1 {
    ParticipantAuthorizationAdded(Box<models::ParticipantAuthorizationAdded>),
    ParticipantAuthorizationChanged(Box<models::ParticipantAuthorizationChanged>),
    ParticipantAuthorizationRevoked(Box<models::ParticipantAuthorizationRevoked>),
}

impl Default for Event1 {
    fn default() -> Self {
        Self::ParticipantAuthorizationAdded(Default::default())
    }
}

