/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExerciseByKeyCommand : Exercise a choice on an existing contract specified by its key.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExerciseByKeyCommand {
    /// The template of contract the client wants to exercise. Both package-name and package-id reference identifier formats for the template-id are supported. Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.  Required
    #[serde(rename = "templateId")]
    pub template_id: String,
    /// The key of the contract the client wants to exercise upon.  Required
    #[serde(rename = "contractKey", deserialize_with = "Option::deserialize")]
    pub contract_key: Option<serde_json::Value>,
    /// The name of the choice the client wants to exercise. Must be a valid NameString (as described in ``value.proto``)  Required
    #[serde(rename = "choice")]
    pub choice: String,
    /// The argument for this choice.  Required
    #[serde(rename = "choiceArgument", deserialize_with = "Option::deserialize")]
    pub choice_argument: Option<serde_json::Value>,
}

impl ExerciseByKeyCommand {
    /// Exercise a choice on an existing contract specified by its key.
    pub fn new(template_id: String, contract_key: Option<serde_json::Value>, choice: String, choice_argument: Option<serde_json::Value>) -> ExerciseByKeyCommand {
        ExerciseByKeyCommand {
            template_id,
            contract_key,
            choice,
            choice_argument,
        }
    }
}

