/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExperimentalCommandInspectionService : Whether the Ledger API supports command inspection service
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExperimentalCommandInspectionService {
    /// 
    #[serde(rename = "supported")]
    pub supported: bool,
}

impl ExperimentalCommandInspectionService {
    /// Whether the Ledger API supports command inspection service
    pub fn new(supported: bool) -> ExperimentalCommandInspectionService {
        ExperimentalCommandInspectionService {
            supported,
        }
    }
}

