/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ExperimentalStaticTime : Ledger is in the static time mode and exposes a time service.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExperimentalStaticTime {
    /// 
    #[serde(rename = "supported")]
    pub supported: bool,
}

impl ExperimentalStaticTime {
    /// Ledger is in the static time mode and exposes a time service.
    pub fn new(supported: bool) -> ExperimentalStaticTime {
        ExperimentalStaticTime {
            supported,
        }
    }
}

