/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct FeaturesDescriptor {
    #[serde(rename = "experimental")]
    pub experimental: Box<models::ExperimentalFeatures>,
    #[serde(rename = "userManagement")]
    pub user_management: Box<models::UserManagementFeature>,
    #[serde(rename = "partyManagement")]
    pub party_management: Box<models::PartyManagementFeature>,
    #[serde(rename = "offsetCheckpoint")]
    pub offset_checkpoint: Box<models::OffsetCheckpointFeature>,
    #[serde(rename = "packageFeature")]
    pub package_feature: Box<models::PackageFeature>,
}

impl FeaturesDescriptor {
    pub fn new(experimental: models::ExperimentalFeatures, user_management: models::UserManagementFeature, party_management: models::PartyManagementFeature, offset_checkpoint: models::OffsetCheckpointFeature, package_feature: models::PackageFeature) -> FeaturesDescriptor {
        FeaturesDescriptor {
            experimental: Box::new(experimental),
            user_management: Box::new(user_management),
            party_management: Box::new(party_management),
            offset_checkpoint: Box::new(offset_checkpoint),
            package_feature: Box::new(package_feature),
        }
    }
}

