/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Field {
    #[serde(rename = "varint", skip_serializing_if = "Option::is_none")]
    pub varint: Option<Vec<i64>>,
    #[serde(rename = "fixed64", skip_serializing_if = "Option::is_none")]
    pub fixed64: Option<Vec<i64>>,
    #[serde(rename = "fixed32", skip_serializing_if = "Option::is_none")]
    pub fixed32: Option<Vec<i32>>,
    #[serde(rename = "lengthDelimited", skip_serializing_if = "Option::is_none")]
    pub length_delimited: Option<Vec<String>>,
}

impl Field {
    pub fn new() -> Field {
        Field {
            varint: None,
            fixed64: None,
            fixed32: None,
            length_delimited: None,
        }
    }
}

