/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenerateExternalPartyTopologyResponse : Response message with topology transactions and the multi-hash to be signed.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateExternalPartyTopologyResponse {
    /// The generated party id  Required
    #[serde(rename = "partyId")]
    pub party_id: String,
    /// The fingerprint of the supplied public key  Required
    #[serde(rename = "publicKeyFingerprint")]
    pub public_key_fingerprint: String,
    /// The serialized topology transactions which need to be signed and submitted as part of the allocate party process Note that the serialization includes the versioning information. Therefore, the transaction here is serialized as an `UntypedVersionedMessage` which in turn contains the serialized `TopologyTransaction` in the version supported by the synchronizer.  Required: must be non-empty
    #[serde(rename = "topologyTransactions")]
    pub topology_transactions: Vec<String>,
    /// the multi-hash which may be signed instead of each individual transaction  Required: must be non-empty
    #[serde(rename = "multiHash")]
    pub multi_hash: String,
}

impl GenerateExternalPartyTopologyResponse {
    /// Response message with topology transactions and the multi-hash to be signed.
    pub fn new(party_id: String, public_key_fingerprint: String, topology_transactions: Vec<String>, multi_hash: String) -> GenerateExternalPartyTopologyResponse {
        GenerateExternalPartyTopologyResponse {
            party_id,
            public_key_fingerprint,
            topology_transactions,
            multi_hash,
        }
    }
}

