/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateExternalPartyTopologyRequest {
    /// Synchronizer-id for which we are building this request. TODO(#27670) support synchronizer aliases  Required
    #[serde(rename = "synchronizer")]
    pub synchronizer: String,
    /// The actual party id will be constructed from this hint and a fingerprint of the public key  Required
    #[serde(rename = "partyHint")]
    pub party_hint: String,
    #[serde(rename = "publicKey")]
    pub public_key: Box<models::SigningPublicKey>,
    /// If true, then the local participant will only be observing, not confirming. Default false.  Optional
    #[serde(rename = "localParticipantObservationOnly", skip_serializing_if = "Option::is_none")]
    pub local_participant_observation_only: Option<bool>,
    /// Other participant ids which should be confirming for this party  Optional: can be empty
    #[serde(rename = "otherConfirmingParticipantUids", skip_serializing_if = "Option::is_none")]
    pub other_confirming_participant_uids: Option<Vec<String>>,
    /// Confirmation threshold >= 1 for the party. Defaults to all available confirmers (or if set to 0).  Optional
    #[serde(rename = "confirmationThreshold", skip_serializing_if = "Option::is_none")]
    pub confirmation_threshold: Option<i32>,
    /// Other observing participant ids for this party  Optional: can be empty
    #[serde(rename = "observingParticipantUids", skip_serializing_if = "Option::is_none")]
    pub observing_participant_uids: Option<Vec<String>>,
}

impl GenerateExternalPartyTopologyRequest {
    pub fn new(synchronizer: String, party_hint: String, public_key: models::SigningPublicKey) -> GenerateExternalPartyTopologyRequest {
        GenerateExternalPartyTopologyRequest {
            synchronizer,
            party_hint,
            public_key: Box::new(public_key),
            local_participant_observation_only: None,
            other_confirming_participant_uids: None,
            confirmation_threshold: None,
            observing_participant_uids: None,
        }
    }
}

