/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetContractRequest {
    /// The ID of the contract. Must be a valid LedgerString (as described in ``value.proto``).  Required
    #[serde(rename = "contractId")]
    pub contract_id: String,
    /// The list of querying parties The stakeholders of the referenced contract must have an intersection with any of these parties to return the result. If no querying_parties specified, all possible contracts could be returned.  Optional: can be empty
    #[serde(rename = "queryingParties", skip_serializing_if = "Option::is_none")]
    pub querying_parties: Option<Vec<String>>,
}

impl GetContractRequest {
    pub fn new(contract_id: String) -> GetContractRequest {
        GetContractRequest {
            contract_id,
            querying_parties: None,
        }
    }
}

