/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetConnectedSynchronizersResponse {
    /// 
    #[serde(rename = "connectedSynchronizers", skip_serializing_if = "Option::is_none")]
    pub connected_synchronizers: Option<Vec<models::ConnectedSynchronizer>>,
}

impl GetConnectedSynchronizersResponse {
    pub fn new() -> GetConnectedSynchronizersResponse {
        GetConnectedSynchronizersResponse {
            connected_synchronizers: None,
        }
    }
}

