/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GetV2JoseJwks200Response : A JWKS as specified by RFC 7517
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetV2JoseJwks200Response {
    /// List of JWKs for the specified party and synchronizer. Only keys of which the usage allows for Party JWT authentication will be returned.  Optional: can be empty
    #[serde(rename = "keys")]
    pub keys: Vec<serde_json::Value>,
}

impl GetV2JoseJwks200Response {
    /// A JWKS as specified by RFC 7517
    pub fn new(keys: Vec<serde_json::Value>) -> GetV2JoseJwks200Response {
        GetV2JoseJwks200Response {
            keys,
        }
    }
}

