/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPartiesResponse {
    /// The details of the requested Daml parties by the participant, if known. The party details may not be in the same order as requested. Required
    #[serde(rename = "partyDetails", skip_serializing_if = "Option::is_none")]
    pub party_details: Option<Vec<models::PartyDetails>>,
}

impl GetPartiesResponse {
    pub fn new() -> GetPartiesResponse {
        GetPartiesResponse {
            party_details: None,
        }
    }
}

