/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdateByIdRequest {
    /// The ID of a particular update. Must be a valid LedgerString (as described in ``value.proto``).  Required
    #[serde(rename = "updateId")]
    pub update_id: String,
    #[serde(rename = "updateFormat")]
    pub update_format: Box<models::UpdateFormat>,
}

impl GetUpdateByIdRequest {
    pub fn new(update_id: String, update_format: models::UpdateFormat) -> GetUpdateByIdRequest {
        GetUpdateByIdRequest {
            update_id,
            update_format: Box::new(update_format),
        }
    }
}

