/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdateByOffsetRequest {
    /// The offset of the update being looked up. Must be a valid absolute offset (positive integer). Required
    #[serde(rename = "offset")]
    pub offset: i64,
    #[serde(rename = "updateFormat", skip_serializing_if = "Option::is_none")]
    pub update_format: Option<Box<models::UpdateFormat>>,
}

impl GetUpdateByOffsetRequest {
    pub fn new(offset: i64) -> GetUpdateByOffsetRequest {
        GetUpdateByOffsetRequest {
            offset,
            update_format: None,
        }
    }
}

