/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdatesRequest {
    /// Beginning of the requested ledger section (non-negative integer). The response will only contain transactions whose offset is strictly greater than this. If zero, the stream will start from the beginning of the ledger. If positive, the streaming will start after this absolute offset. If the ledger has been pruned, this parameter must be specified and be greater than the pruning offset.
    #[serde(rename = "beginExclusive")]
    pub begin_exclusive: i64,
    /// End of the requested ledger section. The response will only contain transactions whose offset is less than or equal to this. Optional, if empty, the stream will not terminate. If specified, the stream will terminate after this absolute offset (positive integer) is reached.
    #[serde(rename = "endInclusive", skip_serializing_if = "Option::is_none")]
    pub end_inclusive: Option<i64>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::TransactionFilter>>,
    /// Provided for backwards compatibility, it will be removed in the Canton version 3.4.0. If enabled, values served over the API will contain more information than strictly necessary to interpret the data. In particular, setting the verbose flag to true triggers the ledger to include labels, record and variant type ids for record fields. Optional for backwards compatibility, if defined update_format must be unset
    #[serde(rename = "verbose")]
    pub verbose: bool,
    #[serde(rename = "updateFormat", skip_serializing_if = "Option::is_none")]
    pub update_format: Option<Box<models::UpdateFormat>>,
}

impl GetUpdatesRequest {
    pub fn new(begin_exclusive: i64, verbose: bool) -> GetUpdatesRequest {
        GetUpdatesRequest {
            begin_exclusive,
            end_inclusive: None,
            filter: None,
            verbose,
            update_format: None,
        }
    }
}

