/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdatesRequest {
    /// Exclusive lower bound offset of the requested ledger section (non-negative integer). The response will only contain transactions whose offset is strictly greater than this. If set to zero, the lower bound is set to the beginning of the ledger. If the participant has been pruned, this parameter must be greater or equal than the pruning offset. Required
    #[serde(rename = "beginExclusive")]
    pub begin_exclusive: i64,
    /// Inclusive higher bound offset of the requested ledger section. If specified the response will only contain transactions whose offset is less than or equal to this. If not specified,  - the descending_order must not be selected, - the stream will not terminate.  Optional
    #[serde(rename = "endInclusive", skip_serializing_if = "Option::is_none")]
    pub end_inclusive: Option<i64>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::TransactionFilter>>,
    /// Provided for backwards compatibility, it will be removed in the Canton version 3.5.0. If enabled, values served over the API will contain more information than strictly necessary to interpret the data. In particular, setting the verbose flag to true triggers the ledger to include labels, record and variant type ids for record fields. Optional for backwards compatibility, if defined update_format must be unset
    #[serde(rename = "verbose", skip_serializing_if = "Option::is_none")]
    pub verbose: Option<bool>,
    #[serde(rename = "updateFormat", skip_serializing_if = "Option::is_none")]
    pub update_format: Option<Box<models::UpdateFormat>>,
    /// If set, the stream will populate the elements in descending order.  Optional
    #[serde(rename = "descendingOrder", skip_serializing_if = "Option::is_none")]
    pub descending_order: Option<bool>,
}

impl GetUpdatesRequest {
    pub fn new(begin_exclusive: i64) -> GetUpdatesRequest {
        GetUpdatesRequest {
            begin_exclusive,
            end_inclusive: None,
            filter: None,
            verbose: None,
            update_format: None,
            descending_order: None,
        }
    }
}

