/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdatesRequest {
    /// Beginning of the requested ledger section (non-negative integer). The response will only contain transactions whose offset is strictly greater than this. If not populated or set to zero, the stream will start from the beginning of the ledger. If positive, the streaming will start after this absolute offset. If the ledger has been pruned, this parameter must be specified and be greater than the pruning offset.  Optional
    #[serde(rename = "beginExclusive", skip_serializing_if = "Option::is_none")]
    pub begin_exclusive: Option<i64>,
    /// End of the requested ledger section. The response will only contain transactions whose offset is less than or equal to this. If empty, the stream will not terminate. If specified, the stream will terminate after this absolute offset (positive integer) is reached.  Optional
    #[serde(rename = "endInclusive", skip_serializing_if = "Option::is_none")]
    pub end_inclusive: Option<i64>,
    #[serde(rename = "filter", skip_serializing_if = "Option::is_none")]
    pub filter: Option<Box<models::TransactionFilter>>,
    /// Provided for backwards compatibility, it will be removed in the Canton version 3.5.0. If enabled, values served over the API will contain more information than strictly necessary to interpret the data. In particular, setting the verbose flag to true triggers the ledger to include labels, record and variant type ids for record fields. Optional for backwards compatibility, if defined update_format must be unset
    #[serde(rename = "verbose", skip_serializing_if = "Option::is_none")]
    pub verbose: Option<bool>,
    #[serde(rename = "updateFormat")]
    pub update_format: Box<models::UpdateFormat>,
}

impl GetUpdatesRequest {
    pub fn new(update_format: models::UpdateFormat) -> GetUpdatesRequest {
        GetUpdatesRequest {
            begin_exclusive: None,
            end_inclusive: None,
            filter: None,
            verbose: None,
            update_format: Box::new(update_format),
        }
    }
}

