/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetParticipantIdResponse {
    /// Identifier of the participant, which SHOULD be globally unique. Must be a valid LedgerString (as describe in ``value.proto``).
    #[serde(rename = "participantId")]
    pub participant_id: String,
}

impl GetParticipantIdResponse {
    pub fn new(participant_id: String) -> GetParticipantIdResponse {
        GetParticipantIdResponse {
            participant_id,
        }
    }
}

