/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetUpdateByIdRequest {
    /// The ID of a particular update. Must be a valid LedgerString (as described in ``value.proto``). Required
    #[serde(rename = "updateId")]
    pub update_id: String,
    #[serde(rename = "updateFormat", skip_serializing_if = "Option::is_none")]
    pub update_format: Option<Box<models::UpdateFormat>>,
}

impl GetUpdateByIdRequest {
    pub fn new(update_id: String) -> GetUpdateByIdRequest {
        GetUpdateByIdRequest {
            update_id,
            update_format: None,
        }
    }
}

