/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetLatestPrunedOffsetsResponse {
    /// It will always be a non-negative integer. If positive, the absolute offset up to which the ledger has been pruned, disregarding the state of all divulged contracts pruning. If zero, the ledger has not been pruned yet.  Optional
    #[serde(rename = "participantPrunedUpToInclusive", skip_serializing_if = "Option::is_none")]
    pub participant_pruned_up_to_inclusive: Option<i64>,
    /// It will always be a non-negative integer. If positive, the absolute offset up to which all divulged events have been pruned on the ledger. It can be at or before the ``participant_pruned_up_to_inclusive`` offset. For more details about all divulged events pruning, see ``PruneRequest.prune_all_divulged_contracts`` in ``participant_pruning_service.proto``. If zero, the divulged events have not been pruned yet.  Optional
    #[serde(rename = "allDivulgedContractsPrunedUpToInclusive", skip_serializing_if = "Option::is_none")]
    pub all_divulged_contracts_pruned_up_to_inclusive: Option<i64>,
}

impl GetLatestPrunedOffsetsResponse {
    pub fn new() -> GetLatestPrunedOffsetsResponse {
        GetLatestPrunedOffsetsResponse {
            participant_pruned_up_to_inclusive: None,
            all_divulged_contracts_pruned_up_to_inclusive: None,
        }
    }
}

