/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetCompletionByHashResponse {
    #[serde(rename = "acceptedCompletion", skip_serializing_if = "Option::is_none")]
    pub accepted_completion: Option<Box<models::Completion1>>,
    /// Recent rejected completions for the given transaction hash, in descending offset order. The server may truncate this list if there are too many entries. Use ``submission_id`` to correlate with a specific command submission. Only completions beyond the current pruning offset are visible.  Optional: can be empty
    #[serde(rename = "lastRejectedCompletions", skip_serializing_if = "Option::is_none")]
    pub last_rejected_completions: Option<Vec<models::Completion1>>,
}

impl GetCompletionByHashResponse {
    pub fn new() -> GetCompletionByHashResponse {
        GetCompletionByHashResponse {
            accepted_completion: None,
            last_rejected_completions: None,
        }
    }
}

