/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPackageStatusResponse {
    /// The status of the package.  Required
    #[serde(rename = "packageStatus")]
    pub package_status: PackageStatus,
}

impl GetPackageStatusResponse {
    pub fn new(package_status: PackageStatus) -> GetPackageStatusResponse {
        GetPackageStatusResponse {
            package_status,
        }
    }
}
/// The status of the package.  Required
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PackageStatus {
    #[serde(rename = "PACKAGE_STATUS_UNSPECIFIED")]
    PackageStatusUnspecified,
    #[serde(rename = "PACKAGE_STATUS_REGISTERED")]
    PackageStatusRegistered,
}

impl Default for PackageStatus {
    fn default() -> PackageStatus {
        Self::PackageStatusUnspecified
    }
}

