/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GetPreferredPackageVersionResponse {
    #[serde(rename = "packagePreference", skip_serializing_if = "Option::is_none")]
    pub package_preference: Option<Box<models::PackagePreference>>,
}

impl GetPreferredPackageVersionResponse {
    pub fn new() -> GetPreferredPackageVersionResponse {
        GetPreferredPackageVersionResponse {
            package_preference: None,
        }
    }
}

