/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GrantUserRightsRequest : Add the rights to the set of rights granted to the user.  Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantUserRightsRequest {
    /// The user to whom to grant rights.  Required
    #[serde(rename = "userId")]
    pub user_id: String,
    /// The rights to grant.  Optional: can be empty
    #[serde(rename = "rights", skip_serializing_if = "Option::is_none")]
    pub rights: Option<Vec<models::Right>>,
    /// The id of the ``Identity Provider`` If not set, assume the user is managed by the default identity provider.  Optional
    #[serde(rename = "identityProviderId", skip_serializing_if = "Option::is_none")]
    pub identity_provider_id: Option<String>,
}

impl GrantUserRightsRequest {
    /// Add the rights to the set of rights granted to the user.  Required authorization: ``HasRight(ParticipantAdmin) OR IsAuthenticatedIdentityProviderAdmin(identity_provider_id)``
    pub fn new(user_id: String) -> GrantUserRightsRequest {
        GrantUserRightsRequest {
            user_id,
            rights: None,
            identity_provider_id: None,
        }
    }
}

