/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GrantUserRightsResponse {
    /// The rights that were newly granted by the request.
    #[serde(rename = "newlyGrantedRights", skip_serializing_if = "Option::is_none")]
    pub newly_granted_rights: Option<Vec<models::Right>>,
}

impl GrantUserRightsResponse {
    pub fn new() -> GrantUserRightsResponse {
        GrantUserRightsResponse {
            newly_granted_rights: None,
        }
    }
}

