/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct HashingSchemeVersionOneOf {
    #[serde(rename = "HASHING_SCHEME_VERSION_UNSPECIFIED")]
    pub hashing_scheme_version_unspecified: serde_json::Value,
}

impl HashingSchemeVersionOneOf {
    pub fn new(hashing_scheme_version_unspecified: serde_json::Value) -> HashingSchemeVersionOneOf {
        HashingSchemeVersionOneOf {
            hashing_scheme_version_unspecified,
        }
    }
}

