/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifierFilterOneOf3 {
    #[serde(rename = "WildcardFilter")]
    pub wildcard_filter: Box<models::WildcardFilter>,
}

impl IdentifierFilterOneOf3 {
    pub fn new(wildcard_filter: models::WildcardFilter) -> IdentifierFilterOneOf3 {
        IdentifierFilterOneOf3 {
            wildcard_filter: Box::new(wildcard_filter),
        }
    }
}

