/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct IdentifierFilterOneOf2 {
    #[serde(rename = "TemplateFilter")]
    pub template_filter: Box<models::TemplateFilter>,
}

impl IdentifierFilterOneOf2 {
    pub fn new(template_filter: models::TemplateFilter) -> IdentifierFilterOneOf2 {
        IdentifierFilterOneOf2 {
            template_filter: Box::new(template_filter),
        }
    }
}

