/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InterfaceFilter1 : This filter matches contracts that implement a specific interface.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterfaceFilter1 {
    /// The interface that a matching contract must implement. The ``interface_id`` needs to be valid: corresponding interface should be defined in one of the available packages at the time of the query. Both package-name and package-id reference formats for the identifier are supported. Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.  Required
    #[serde(rename = "interfaceId", skip_serializing_if = "Option::is_none")]
    pub interface_id: Option<String>,
    /// Whether to include the interface view on the contract in the returned ``CreatedEvent``. Use this to access contract data in a uniform manner in your API client. Optional
    #[serde(rename = "includeInterfaceView")]
    pub include_interface_view: bool,
    /// Whether to include a ``created_event_blob`` in the returned ``CreatedEvent``. Use this to access the contract create event payload in your API client for submitting it as a disclosed contract with future commands. Optional
    #[serde(rename = "includeCreatedEventBlob")]
    pub include_created_event_blob: bool,
}

impl InterfaceFilter1 {
    /// This filter matches contracts that implement a specific interface.
    pub fn new(include_interface_view: bool, include_created_event_blob: bool) -> InterfaceFilter1 {
        InterfaceFilter1 {
            interface_id: None,
            include_interface_view,
            include_created_event_blob,
        }
    }
}

