/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InterfaceFilter1 : This filter matches contracts that implement a specific interface.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterfaceFilter1 {
    /// The interface that a matching contract must implement. The ``interface_id`` needs to be valid: corresponding interface should be defined in one of the available packages at the time of the query. Both package-name and package-id reference formats for the identifier are supported. Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.  Required
    #[serde(rename = "interfaceId")]
    pub interface_id: String,
    /// Whether to include the interface view on the contract in the returned ``CreatedEvent``. Use this to access contract data in a uniform manner in your API client.  Optional
    #[serde(rename = "includeInterfaceView", skip_serializing_if = "Option::is_none")]
    pub include_interface_view: Option<bool>,
    /// Whether to include a ``created_event_blob`` in the returned ``CreatedEvent``. Use this to access the contract create event payload in your API client for submitting it as a disclosed contract with future commands.  Optional
    #[serde(rename = "includeCreatedEventBlob", skip_serializing_if = "Option::is_none")]
    pub include_created_event_blob: Option<bool>,
}

impl InterfaceFilter1 {
    /// This filter matches contracts that implement a specific interface.
    pub fn new(interface_id: String) -> InterfaceFilter1 {
        InterfaceFilter1 {
            interface_id,
            include_interface_view: None,
            include_created_event_blob: None,
        }
    }
}

