/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InterfaceFilter : This filter matches contracts that implement a specific interface.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InterfaceFilter {
    #[serde(rename = "value")]
    pub value: Box<models::InterfaceFilter1>,
}

impl InterfaceFilter {
    /// This filter matches contracts that implement a specific interface.
    pub fn new(value: models::InterfaceFilter1) -> InterfaceFilter {
        InterfaceFilter {
            value: Box::new(value),
        }
    }
}

