/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsAssignmentEvent {
    #[serde(rename = "source")]
    pub source: String,
    #[serde(rename = "target")]
    pub target: String,
    #[serde(rename = "reassignmentId")]
    pub reassignment_id: String,
    #[serde(rename = "submitter")]
    pub submitter: String,
    #[serde(rename = "reassignmentCounter")]
    pub reassignment_counter: i64,
    #[serde(rename = "createdEvent")]
    pub created_event: Box<models::CreatedEvent>,
}

impl JsAssignmentEvent {
    pub fn new(source: String, target: String, reassignment_id: String, submitter: String, reassignment_counter: i64, created_event: models::CreatedEvent) -> JsAssignmentEvent {
        JsAssignmentEvent {
            source,
            target,
            reassignment_id,
            submitter,
            reassignment_counter,
            created_event: Box::new(created_event),
        }
    }
}

