/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsActiveContract {
    #[serde(rename = "createdEvent")]
    pub created_event: Box<models::CreatedEvent>,
    /// A valid synchronizer id  Required
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// The reassignment counter of this event.  Reassignment counters strictly increase with each unassign command for the same contract. Creation of the contract corresponds to a reassignment_counter equal to zero. This field will be the reassignment_counter of the latest observable activation event on this synchronizer, which is before the active_at_offset.  Required
    #[serde(rename = "reassignmentCounter")]
    pub reassignment_counter: i64,
}

impl JsActiveContract {
    pub fn new(created_event: models::CreatedEvent, synchronizer_id: String, reassignment_counter: i64) -> JsActiveContract {
        JsActiveContract {
            created_event: Box::new(created_event),
            synchronizer_id,
            reassignment_counter,
        }
    }
}

