/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsContractEntryOneOf1 {
    #[serde(rename = "JsEmpty")]
    pub js_empty: serde_json::Value,
}

impl JsContractEntryOneOf1 {
    pub fn new(js_empty: serde_json::Value) -> JsContractEntryOneOf1 {
        JsContractEntryOneOf1 {
            js_empty,
        }
    }
}

