/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsCreated {
    #[serde(rename = "createdEvent")]
    pub created_event: Box<models::CreatedEvent>,
    /// The synchronizer which sequenced the creation of the contract  Required
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
}

impl JsCreated {
    pub fn new(created_event: models::CreatedEvent, synchronizer_id: String) -> JsCreated {
        JsCreated {
            created_event: Box::new(created_event),
            synchronizer_id,
        }
    }
}

