/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsContractEntryOneOf {
    #[serde(rename = "JsActiveContract")]
    pub js_active_contract: Box<models::JsActiveContract>,
}

impl JsContractEntryOneOf {
    pub fn new(js_active_contract: models::JsActiveContract) -> JsContractEntryOneOf {
        JsContractEntryOneOf {
            js_active_contract: Box::new(js_active_contract),
        }
    }
}

