/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsContractEntry : For a contract there could be multiple contract_entry-s in the entire snapshot. These together define the state of one contract in the snapshot. A contract_entry is included in the result, if and only if there is at least one stakeholder party of the contract that is hosted on the synchronizer at the time of the event and the party satisfies the ``TransactionFilter`` in the query.  Required
/// For a contract there could be multiple contract_entry-s in the entire snapshot. These together define the state of one contract in the snapshot. A contract_entry is included in the result, if and only if there is at least one stakeholder party of the contract that is hosted on the synchronizer at the time of the event and the party satisfies the ``TransactionFilter`` in the query.  Required
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsContractEntry {
    JsContractEntryOneOf(Box<models::JsContractEntryOneOf>),
    JsContractEntryOneOf1(Box<models::JsContractEntryOneOf1>),
    JsContractEntryOneOf2(Box<models::JsContractEntryOneOf2>),
    JsContractEntryOneOf3(Box<models::JsContractEntryOneOf3>),
}

impl Default for JsContractEntry {
    fn default() -> Self {
        Self::JsContractEntryOneOf(Default::default())
    }
}

