/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsContractEntry : For a contract there could be multiple contract_entry-s in the entire snapshot. These together define the state of one contract in the snapshot. A contract_entry is included in the result, if and only if there is at least one stakeholder party of the contract that is hosted on the synchronizer at the time of the event and the party satisfies the ``TransactionFilter`` in the query.
/// For a contract there could be multiple contract_entry-s in the entire snapshot. These together define the state of one contract in the snapshot. A contract_entry is included in the result, if and only if there is at least one stakeholder party of the contract that is hosted on the synchronizer at the time of the event and the party satisfies the ``TransactionFilter`` in the query.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsContractEntry {
    JsContractEntryOneOf(Box<models::JsContractEntryOneOf>),
    JsContractEntryOneOf1(Box<models::JsContractEntryOneOf1>),
    JsContractEntryOneOf2(Box<models::JsContractEntryOneOf2>),
    JsContractEntryOneOf3(Box<models::JsContractEntryOneOf3>),
}

impl Default for JsContractEntry {
    fn default() -> Self {
        Self::JsContractEntryOneOf(Default::default())
    }
}

