/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsGetActiveContractsResponse {
    /// The workflow ID used in command submission which corresponds to the contract_entry. Only set if the ``workflow_id`` for the command was set. Must be a valid LedgerString (as described in ``value.proto``). Optional
    #[serde(rename = "workflowId")]
    pub workflow_id: String,
    #[serde(rename = "contractEntry")]
    pub contract_entry: Box<models::JsContractEntry>,
}

impl JsGetActiveContractsResponse {
    pub fn new(workflow_id: String, contract_entry: models::JsContractEntry) -> JsGetActiveContractsResponse {
        JsGetActiveContractsResponse {
            workflow_id,
            contract_entry: Box::new(contract_entry),
        }
    }
}

