/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsGetTransactionTreeResponse : Provided for backwards compatibility, it will be removed in the Canton version 3.4.0.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsGetTransactionTreeResponse {
    #[serde(rename = "transaction")]
    pub transaction: Box<models::JsTransactionTree>,
}

impl JsGetTransactionTreeResponse {
    /// Provided for backwards compatibility, it will be removed in the Canton version 3.4.0.
    pub fn new(transaction: models::JsTransactionTree) -> JsGetTransactionTreeResponse {
        JsGetTransactionTreeResponse {
            transaction: Box::new(transaction),
        }
    }
}

