/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsInterfaceView : View of a create event matched by an interface filter.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsInterfaceView {
    /// The interface implemented by the matched event. The identifier uses the package-id reference format.  Required
    #[serde(rename = "interfaceId")]
    pub interface_id: String,
    #[serde(rename = "viewStatus")]
    pub view_status: Box<models::JsStatus>,
    /// The value of the interface's view method on this event. Set if it was requested in the ``InterfaceFilter`` and it could be successfully computed.  Optional
    #[serde(rename = "viewValue", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub view_value: Option<Option<serde_json::Value>>,
    /// The package defining the interface implementation used to compute the view. Can be different from the package that was used to create the contract itself, as the contract arguments can be upgraded or downgraded using smart-contract upgrading as part of computing the interface view. Populated if the view computation is successful, otherwise empty.  Optional
    #[serde(rename = "implementationPackageId", skip_serializing_if = "Option::is_none")]
    pub implementation_package_id: Option<String>,
}

impl JsInterfaceView {
    /// View of a create event matched by an interface filter.
    pub fn new(interface_id: String, view_status: models::JsStatus) -> JsInterfaceView {
        JsInterfaceView {
            interface_id,
            view_status: Box::new(view_status),
            view_value: None,
            implementation_package_id: None,
        }
    }
}

