/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsIncompleteUnassigned {
    #[serde(rename = "createdEvent")]
    pub created_event: Box<models::CreatedEvent>,
    #[serde(rename = "unassignedEvent")]
    pub unassigned_event: Box<models::UnassignedEvent>,
}

impl JsIncompleteUnassigned {
    pub fn new(created_event: models::CreatedEvent, unassigned_event: models::UnassignedEvent) -> JsIncompleteUnassigned {
        JsIncompleteUnassigned {
            created_event: Box::new(created_event),
            unassigned_event: Box::new(unassigned_event),
        }
    }
}

