/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsPrepareSubmissionRequest {
    /// Uniquely identifies the participant user that prepares the transaction. Must be a valid UserIdString (as described in ``value.proto``). Required unless authentication is used with a user token. In that case, the token's user-id will be used for the request's user_id.
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Uniquely identifies the command. The triple (user_id, act_as, command_id) constitutes the change ID for the intended ledger change, where act_as is interpreted as a set of party names. The change ID can be used for matching the intended ledger changes with all their completions. Must be a valid LedgerString (as described in ``value.proto``). Required
    #[serde(rename = "commandId")]
    pub command_id: String,
    /// Individual elements of this atomic command. Must be non-empty. Required
    #[serde(rename = "commands", skip_serializing_if = "Option::is_none")]
    pub commands: Option<Vec<models::Command>>,
    #[serde(rename = "minLedgerTime", skip_serializing_if = "Option::is_none")]
    pub min_ledger_time: Option<Box<models::MinLedgerTime>>,
    /// Set of parties on whose behalf the command should be executed, if submitted. If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request to **read** (not act) on behalf of each of the given parties. This is because this RPC merely prepares a transaction and does not execute it. Therefore read authorization is sufficient even for actAs parties. Note: This may change, and more specific authorization scope may be introduced in the future. Each element must be a valid PartyIdString (as described in ``value.proto``). Required, must be non-empty.
    #[serde(rename = "actAs", skip_serializing_if = "Option::is_none")]
    pub act_as: Option<Vec<String>>,
    /// Set of parties on whose behalf (in addition to all parties listed in ``act_as``) contracts can be retrieved. This affects Daml operations such as ``fetch``, ``fetchByKey``, ``lookupByKey``, ``exercise``, and ``exerciseByKey``. Note: A command can only use contracts that are visible to at least one of the parties in ``act_as`` or ``read_as``. This visibility check is independent from the Daml authorization rules for fetch operations. If ledger API authorization is enabled, then the authorization metadata must authorize the sender of the request to read contract data on behalf of each of the given parties. Optional
    #[serde(rename = "readAs", skip_serializing_if = "Option::is_none")]
    pub read_as: Option<Vec<String>>,
    /// Additional contracts used to resolve contract & contract key lookups. Optional
    #[serde(rename = "disclosedContracts", skip_serializing_if = "Option::is_none")]
    pub disclosed_contracts: Option<Vec<models::DisclosedContract>>,
    /// Must be a valid synchronizer id Required
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// The package-id selection preference of the client for resolving package names and interface instances in command submission and interpretation
    #[serde(rename = "packageIdSelectionPreference", skip_serializing_if = "Option::is_none")]
    pub package_id_selection_preference: Option<Vec<String>>,
    /// When true, the response will contain additional details on how the transaction was encoded and hashed This can be useful for troubleshooting of hash mismatches. Should only be used for debugging.
    #[serde(rename = "verboseHashing")]
    pub verbose_hashing: bool,
}

impl JsPrepareSubmissionRequest {
    pub fn new(user_id: String, command_id: String, synchronizer_id: String, verbose_hashing: bool) -> JsPrepareSubmissionRequest {
        JsPrepareSubmissionRequest {
            user_id,
            command_id,
            commands: None,
            min_ledger_time: None,
            act_as: None,
            read_as: None,
            disclosed_contracts: None,
            synchronizer_id,
            package_id_selection_preference: None,
            verbose_hashing,
        }
    }
}

