/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum JsReassignmentEvent {
    JsAssignmentEvent(Box<models::JsAssignmentEvent>),
    JsUnassignedEvent(Box<models::JsUnassignedEvent>),
}

impl Default for JsReassignmentEvent {
    fn default() -> Self {
        Self::JsAssignmentEvent(Default::default())
    }
}

