/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsSubmitAndWaitForTransactionRequest : These commands are executed as a single atomic transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsSubmitAndWaitForTransactionRequest {
    #[serde(rename = "commands")]
    pub commands: Box<models::JsCommands>,
    #[serde(rename = "transactionFormat")]
    pub transaction_format: Box<models::TransactionFormat>,
}

impl JsSubmitAndWaitForTransactionRequest {
    /// These commands are executed as a single atomic transaction.
    pub fn new(commands: models::JsCommands, transaction_format: models::TransactionFormat) -> JsSubmitAndWaitForTransactionRequest {
        JsSubmitAndWaitForTransactionRequest {
            commands: Box::new(commands),
            transaction_format: Box::new(transaction_format),
        }
    }
}

