/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsSubmitAndWaitForTransactionRequest : These commands are executed as a single atomic transaction.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsSubmitAndWaitForTransactionRequest {
    #[serde(rename = "commands")]
    pub commands: Box<models::JsCommands>,
    #[serde(rename = "transactionFormat", skip_serializing_if = "Option::is_none")]
    pub transaction_format: Option<Box<models::TransactionFormat>>,
}

impl JsSubmitAndWaitForTransactionRequest {
    /// These commands are executed as a single atomic transaction.
    pub fn new(commands: models::JsCommands) -> JsSubmitAndWaitForTransactionRequest {
        JsSubmitAndWaitForTransactionRequest {
            commands: Box::new(commands),
            transaction_format: None,
        }
    }
}

