/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsSubmitAndWaitForTransactionTreeResponse : Deprecated: disabled unless `canton.participants.<participant>.features.deprecated.enable-deprecated-endpoints-34 = true`; it will be removed in the Canton version 3.7.0.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsSubmitAndWaitForTransactionTreeResponse {
    #[serde(rename = "transactionTree", skip_serializing_if = "Option::is_none")]
    pub transaction_tree: Option<Box<models::JsTransactionTree>>,
}

impl JsSubmitAndWaitForTransactionTreeResponse {
    /// Deprecated: disabled unless `canton.participants.<participant>.features.deprecated.enable-deprecated-endpoints-34 = true`; it will be removed in the Canton version 3.7.0.
    pub fn new() -> JsSubmitAndWaitForTransactionTreeResponse {
        JsSubmitAndWaitForTransactionTreeResponse {
            transaction_tree: None,
        }
    }
}

