/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsSubmitAndWaitForReassignmentResponse {
    #[serde(rename = "reassignment")]
    pub reassignment: Box<models::JsReassignment>,
}

impl JsSubmitAndWaitForReassignmentResponse {
    pub fn new(reassignment: models::JsReassignment) -> JsSubmitAndWaitForReassignmentResponse {
        JsSubmitAndWaitForReassignmentResponse {
            reassignment: Box::new(reassignment),
        }
    }
}

