/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// JsUnassignedEvent : Records that a contract has been unassigned, and it becomes unusable on the source synchronizer
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct JsUnassignedEvent {
    #[serde(rename = "value")]
    pub value: Box<models::UnassignedEvent>,
}

impl JsUnassignedEvent {
    /// Records that a contract has been unassigned, and it becomes unusable on the source synchronizer
    pub fn new(value: models::UnassignedEvent) -> JsUnassignedEvent {
        JsUnassignedEvent {
            value: Box::new(value),
        }
    }
}

