/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct KindOneOf2 {
    #[serde(rename = "CanReadAsAnyParty")]
    pub can_read_as_any_party: Box<models::CanReadAsAnyParty>,
}

impl KindOneOf2 {
    pub fn new(can_read_as_any_party: models::CanReadAsAnyParty) -> KindOneOf2 {
        KindOneOf2 {
            can_read_as_any_party: Box::new(can_read_as_any_party),
        }
    }
}

