/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVettedPackagesResponse {
    /// All ``VettedPackages`` that contain at least one ``VettedPackage`` matching both a ``PackageMetadataFilter`` and a ``TopologyStateFilter``. Sorted by synchronizer_id then participant_id.  Optional: can be empty
    #[serde(rename = "vettedPackages", skip_serializing_if = "Option::is_none")]
    pub vetted_packages: Option<Vec<models::VettedPackages>>,
    /// Pagination token to retrieve the next page. Empty string if there are no further results.  Optional
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListVettedPackagesResponse {
    pub fn new() -> ListVettedPackagesResponse {
        ListVettedPackagesResponse {
            vetted_packages: None,
            next_page_token: None,
        }
    }
}

