/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKnownPartiesResponse {
    /// The details of all Daml parties known by the participant.  Required: must be non-empty
    #[serde(rename = "partyDetails")]
    pub party_details: Vec<models::PartyDetails>,
    /// Pagination token to retrieve the next page. Empty, if there are no further results.  Optional
    #[serde(rename = "nextPageToken", skip_serializing_if = "Option::is_none")]
    pub next_page_token: Option<String>,
}

impl ListKnownPartiesResponse {
    pub fn new(party_details: Vec<models::PartyDetails>) -> ListKnownPartiesResponse {
        ListKnownPartiesResponse {
            party_details,
            next_page_token: None,
        }
    }
}

