/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListKnownPartiesResponse {
    /// The details of all Daml parties known by the participant. Required
    #[serde(rename = "partyDetails", skip_serializing_if = "Option::is_none")]
    pub party_details: Option<Vec<models::PartyDetails>>,
    /// Pagination token to retrieve the next page. Empty, if there are no further results.
    #[serde(rename = "nextPageToken")]
    pub next_page_token: String,
}

impl ListKnownPartiesResponse {
    pub fn new(next_page_token: String) -> ListKnownPartiesResponse {
        ListKnownPartiesResponse {
            party_details: None,
            next_page_token,
        }
    }
}

