/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListVettedPackagesRequest {
    #[serde(rename = "packageMetadataFilter", skip_serializing_if = "Option::is_none")]
    pub package_metadata_filter: Option<Box<models::PackageMetadataFilter>>,
    #[serde(rename = "topologyStateFilter", skip_serializing_if = "Option::is_none")]
    pub topology_state_filter: Option<Box<models::TopologyStateFilter>>,
    /// Pagination token to determine the specific page to fetch. Using the token guarantees that ``VettedPackages`` on a subsequent page are all greater (``VettedPackages`` are sorted by synchronizer ID then participant ID) than the last ``VettedPackages`` on a previous page.  The server does not store intermediate results between calls chained by a series of page tokens. As a consequence, if new vetted packages are being added and a page is requested twice using the same token, more packages can be returned on the second call.  Leave unspecified (i.e. as empty string) to fetch the first page.  Optional
    #[serde(rename = "pageToken", skip_serializing_if = "Option::is_none")]
    pub page_token: Option<String>,
    /// Maximum number of ``VettedPackages`` results to return in a single page.  If the page_size is unspecified (i.e. left as 0), the server will decide the number of results to be returned.  If the page_size exceeds the maximum supported by the server, an error will be returned.  To obtain the server's maximum consult the PackageService descriptor available in the VersionService.  Optional
    #[serde(rename = "pageSize", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<i32>,
}

impl ListVettedPackagesRequest {
    pub fn new() -> ListVettedPackagesRequest {
        ListVettedPackagesRequest {
            package_metadata_filter: None,
            topology_state_filter: None,
            page_token: None,
            page_size: None,
        }
    }
}

