/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ListPackagesResponse {
    /// The IDs of all Daml-LF packages supported by the server. Each element must be a valid PackageIdString (as described in ``value.proto``). Required
    #[serde(rename = "packageIds", skip_serializing_if = "Option::is_none")]
    pub package_ids: Option<Vec<String>>,
}

impl ListPackagesResponse {
    pub fn new() -> ListPackagesResponse {
        ListPackagesResponse {
            package_ids: None,
        }
    }
}

