/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MinLedgerTime {
    #[serde(rename = "time")]
    pub time: Box<models::Time>,
}

impl MinLedgerTime {
    pub fn new(time: models::Time) -> MinLedgerTime {
        MinLedgerTime {
            time: Box::new(time),
        }
    }
}

