/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffsetCheckpointFeature {
    #[serde(rename = "maxOffsetCheckpointEmissionDelay")]
    pub max_offset_checkpoint_emission_delay: Box<models::Duration>,
}

impl OffsetCheckpointFeature {
    pub fn new(max_offset_checkpoint_emission_delay: models::Duration) -> OffsetCheckpointFeature {
        OffsetCheckpointFeature {
            max_offset_checkpoint_emission_delay: Box::new(max_offset_checkpoint_emission_delay),
        }
    }
}

