/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffsetCheckpointFeature {
    #[serde(rename = "maxOffsetCheckpointEmissionDelay", skip_serializing_if = "Option::is_none")]
    pub max_offset_checkpoint_emission_delay: Option<Box<models::Duration>>,
}

impl OffsetCheckpointFeature {
    pub fn new() -> OffsetCheckpointFeature {
        OffsetCheckpointFeature {
            max_offset_checkpoint_emission_delay: None,
        }
    }
}

