/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OffsetCheckpoint3 : OffsetCheckpoints may be used to:  - detect time out of commands. - provide an offset which can be used to restart consumption.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffsetCheckpoint3 {
    #[serde(rename = "value")]
    pub value: Box<models::OffsetCheckpoint1>,
}

impl OffsetCheckpoint3 {
    /// OffsetCheckpoints may be used to:  - detect time out of commands. - provide an offset which can be used to restart consumption.
    pub fn new(value: models::OffsetCheckpoint1) -> OffsetCheckpoint3 {
        OffsetCheckpoint3 {
            value: Box::new(value),
        }
    }
}

