/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OffsetCheckpoint1 : OffsetCheckpoints may be used to:  - detect time out of commands. - provide an offset which can be used to restart consumption.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffsetCheckpoint1 {
    /// The participant's offset, the details of the offset field are described in ``community/ledger-api/README.md``. Required, must be a valid absolute offset (positive integer).
    #[serde(rename = "offset")]
    pub offset: i64,
    /// 
    #[serde(rename = "synchronizerTimes", skip_serializing_if = "Option::is_none")]
    pub synchronizer_times: Option<Vec<models::SynchronizerTime>>,
}

impl OffsetCheckpoint1 {
    /// OffsetCheckpoints may be used to:  - detect time out of commands. - provide an offset which can be used to restart consumption.
    pub fn new(offset: i64) -> OffsetCheckpoint1 {
        OffsetCheckpoint1 {
            offset,
            synchronizer_times: None,
        }
    }
}

