/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// OffsetCheckpoint1 : OffsetCheckpoints may be used to:  - detect time out of commands. - provide an offset which can be used to restart consumption.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OffsetCheckpoint1 {
    /// The participant's offset, the details of the offset field are described in ``community/ledger-api/README.md``. Must be a valid absolute offset (positive integer).  Required
    #[serde(rename = "offset")]
    pub offset: i64,
    /// The times associated with each synchronizer at this offset.  Optional: can be empty
    #[serde(rename = "synchronizerTimes", skip_serializing_if = "Option::is_none")]
    pub synchronizer_times: Option<Vec<models::SynchronizerTime>>,
}

impl OffsetCheckpoint1 {
    /// OffsetCheckpoints may be used to:  - detect time out of commands. - provide an offset which can be used to restart consumption.
    pub fn new(offset: i64) -> OffsetCheckpoint1 {
        OffsetCheckpoint1 {
            offset,
            synchronizer_times: None,
        }
    }
}

