/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageStatusOneOf2 {
    #[serde(rename = "Recognized")]
    pub recognized: Box<models::Recognized>,
}

impl PackageStatusOneOf2 {
    pub fn new(recognized: models::Recognized) -> PackageStatusOneOf2 {
        PackageStatusOneOf2 {
            recognized: Box::new(recognized),
        }
    }
}

