/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PackageVettingRequirement : Defines a package-name for which the commonly vetted package with the highest version must be found.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageVettingRequirement {
    /// The parties whose participants' vetting state should be considered when resolving the preferred package.  Required: must be non-empty
    #[serde(rename = "parties")]
    pub parties: Vec<String>,
    /// The package-name for which the preferred package should be resolved.  Required
    #[serde(rename = "packageName")]
    pub package_name: String,
}

impl PackageVettingRequirement {
    /// Defines a package-name for which the commonly vetted package with the highest version must be found.
    pub fn new(parties: Vec<String>, package_name: String) -> PackageVettingRequirement {
        PackageVettingRequirement {
            parties,
            package_name,
        }
    }
}

