/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackagePreference {
    #[serde(rename = "packageReference")]
    pub package_reference: Box<models::PackageReference>,
    /// The synchronizer for which the preferred package was computed. If the synchronizer_id was specified in the request, then it matches the request synchronizer_id.  Required
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
}

impl PackagePreference {
    pub fn new(package_reference: models::PackageReference, synchronizer_id: String) -> PackagePreference {
        PackagePreference {
            package_reference: Box::new(package_reference),
            synchronizer_id,
        }
    }
}

