/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageStatusOneOf {
    #[serde(rename = "PACKAGE_STATUS_REGISTERED")]
    pub package_status_registered: serde_json::Value,
}

impl PackageStatusOneOf {
    pub fn new(package_status_registered: serde_json::Value) -> PackageStatusOneOf {
        PackageStatusOneOf {
            package_status_registered,
        }
    }
}

