/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PackageReference {
    /// Required
    #[serde(rename = "packageId")]
    pub package_id: String,
    /// Required
    #[serde(rename = "packageName")]
    pub package_name: String,
    /// Required
    #[serde(rename = "packageVersion")]
    pub package_version: String,
}

impl PackageReference {
    pub fn new(package_id: String, package_name: String, package_version: String) -> PackageReference {
        PackageReference {
            package_id,
            package_name,
            package_version,
        }
    }
}

