/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ParticipantAuthorizationTopologyFormat : A format specifying which participant authorization topology transactions to include and how to render them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantAuthorizationTopologyFormat {
    /// List of parties for which the topology transactions should be sent. Empty means: for all parties.  Optional: can be empty
    #[serde(rename = "parties", skip_serializing_if = "Option::is_none")]
    pub parties: Option<Vec<String>>,
}

impl ParticipantAuthorizationTopologyFormat {
    /// A format specifying which participant authorization topology transactions to include and how to render them.
    pub fn new() -> ParticipantAuthorizationTopologyFormat {
        ParticipantAuthorizationTopologyFormat {
            parties: None,
        }
    }
}

