/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantPermissionOneOf5 {
    #[serde(rename = "Unrecognized")]
    pub unrecognized: Box<models::Unrecognized2>,
}

impl ParticipantPermissionOneOf5 {
    pub fn new(unrecognized: models::Unrecognized2) -> ParticipantPermissionOneOf5 {
        ParticipantPermissionOneOf5 {
            unrecognized: Box::new(unrecognized),
        }
    }
}

