/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantPermissionOneOf3 {
    #[serde(rename = "PARTICIPANT_PERMISSION_UNSPECIFIED")]
    pub participant_permission_unspecified: serde_json::Value,
}

impl ParticipantPermissionOneOf3 {
    pub fn new(participant_permission_unspecified: serde_json::Value) -> ParticipantPermissionOneOf3 {
        ParticipantPermissionOneOf3 {
            participant_permission_unspecified,
        }
    }
}

