/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantAuthorizationRevoked {
    /// Required
    #[serde(rename = "partyId")]
    pub party_id: String,
    /// Required
    #[serde(rename = "participantId")]
    pub participant_id: String,
}

impl ParticipantAuthorizationRevoked {
    pub fn new(party_id: String, participant_id: String) -> ParticipantAuthorizationRevoked {
        ParticipantAuthorizationRevoked {
            party_id,
            participant_id,
        }
    }
}

