/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartyDetails {
    /// The stable unique identifier of a Daml party. Must be a valid PartyIdString (as described in ``value.proto``).  Required
    #[serde(rename = "party")]
    pub party: String,
    /// true if party is hosted by the participant and the party shares the same identity provider as the user issuing the request.  Optional
    #[serde(rename = "isLocal", skip_serializing_if = "Option::is_none")]
    pub is_local: Option<bool>,
    #[serde(rename = "localMetadata", skip_serializing_if = "Option::is_none")]
    pub local_metadata: Option<Box<models::ObjectMeta>>,
    /// The id of the ``Identity Provider`` Optional, if not set, there could be 3 options:  1. the party is managed by the default identity provider. 2. party is not hosted by the participant. 3. party is hosted by the participant, but is outside of the user's identity provider.  Optional
    #[serde(rename = "identityProviderId", skip_serializing_if = "Option::is_none")]
    pub identity_provider_id: Option<String>,
}

impl PartyDetails {
    pub fn new(party: String) -> PartyDetails {
        PartyDetails {
            party,
            is_local: None,
            local_metadata: None,
            identity_provider_id: None,
        }
    }
}

