/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ParticipantAuthorizationChanged1 {
    /// Required
    #[serde(rename = "partyId")]
    pub party_id: String,
    /// Required
    #[serde(rename = "participantId")]
    pub participant_id: String,
    /// Required
    #[serde(rename = "participantPermission")]
    pub participant_permission: ParticipantPermission,
}

impl ParticipantAuthorizationChanged1 {
    pub fn new(party_id: String, participant_id: String, participant_permission: ParticipantPermission) -> ParticipantAuthorizationChanged1 {
        ParticipantAuthorizationChanged1 {
            party_id,
            participant_id,
            participant_permission,
        }
    }
}
/// Required
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ParticipantPermission {
    #[serde(rename = "PARTICIPANT_PERMISSION_UNSPECIFIED")]
    ParticipantPermissionUnspecified,
    #[serde(rename = "PARTICIPANT_PERMISSION_SUBMISSION")]
    ParticipantPermissionSubmission,
    #[serde(rename = "PARTICIPANT_PERMISSION_CONFIRMATION")]
    ParticipantPermissionConfirmation,
    #[serde(rename = "PARTICIPANT_PERMISSION_OBSERVATION")]
    ParticipantPermissionObservation,
}

impl Default for ParticipantPermission {
    fn default() -> ParticipantPermission {
        Self::ParticipantPermissionUnspecified
    }
}

