/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PrefetchContractKey : Preload contracts
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrefetchContractKey {
    /// The template of contract the client wants to prefetch. Both package-name and package-id reference identifier formats for the template-id are supported. Note: The package-id reference identifier format is deprecated. We plan to end support for this format in version 3.4.  Required
    #[serde(rename = "templateId")]
    pub template_id: String,
    /// The key of the contract the client wants to prefetch.  Required
    #[serde(rename = "contractKey", deserialize_with = "Option::deserialize")]
    pub contract_key: Option<serde_json::Value>,
    /// The number of contracts to prefetch for this key, if available. This is in addition to disclosed contracts. - for backward compatibility reason, absence is interpreted as 1 - 0 is forbidden - capped at 2^31 - 1. The system may impose further limits.  Optional
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
}

impl PrefetchContractKey {
    /// Preload contracts
    pub fn new(template_id: String, contract_key: Option<serde_json::Value>) -> PrefetchContractKey {
        PrefetchContractKey {
            template_id,
            contract_key,
            limit: None,
        }
    }
}

