/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PriorTopologySerial : The serial of last ``VettedPackages`` topology transaction on a given participant and synchronizer.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PriorTopologySerial {
    #[serde(rename = "serial", skip_serializing_if = "Option::is_none")]
    pub serial: Option<Box<models::Serial>>,
}

impl PriorTopologySerial {
    /// The serial of last ``VettedPackages`` topology transaction on a given participant and synchronizer.
    pub fn new() -> PriorTopologySerial {
        PriorTopologySerial {
            serial: None,
        }
    }
}

