/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ProtoAny {
    #[serde(rename = "typeUrl")]
    pub type_url: String,
    #[serde(rename = "value")]
    pub value: String,
    #[serde(rename = "unknownFields")]
    pub unknown_fields: Box<models::UnknownFieldSet>,
    #[serde(rename = "valueDecoded", skip_serializing_if = "Option::is_none")]
    pub value_decoded: Option<String>,
}

impl ProtoAny {
    pub fn new(type_url: String, value: String, unknown_fields: models::UnknownFieldSet) -> ProtoAny {
        ProtoAny {
            type_url,
            value,
            unknown_fields: Box::new(unknown_fields),
            value_decoded: None,
        }
    }
}

