/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReassignmentCommand {
    #[serde(rename = "command")]
    pub command: Box<models::Command1>,
}

impl ReassignmentCommand {
    pub fn new(command: models::Command1) -> ReassignmentCommand {
        ReassignmentCommand {
            command: Box::new(command),
        }
    }
}

