/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Reassignment1 : Complete view of an on-ledger reassignment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Reassignment1 {
    #[serde(rename = "value")]
    pub value: Box<models::JsReassignment>,
}

impl Reassignment1 {
    /// Complete view of an on-ledger reassignment.
    pub fn new(value: models::JsReassignment) -> Reassignment1 {
        Reassignment1 {
            value: Box::new(value),
        }
    }
}

