/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RevokeUserRightsResponse {
    /// The rights that were actually revoked by the request.
    #[serde(rename = "newlyRevokedRights", skip_serializing_if = "Option::is_none")]
    pub newly_revoked_rights: Option<Vec<models::Right>>,
}

impl RevokeUserRightsResponse {
    pub fn new() -> RevokeUserRightsResponse {
        RevokeUserRightsResponse {
            newly_revoked_rights: None,
        }
    }
}

