/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SigningAlgorithmSpec {
    SigningAlgorithmSpecEcDsaSha256(serde_json::Value),
    SigningAlgorithmSpecEcDsaSha384(serde_json::Value),
    SigningAlgorithmSpecEd25519(serde_json::Value),
    SigningAlgorithmSpecUnspecified(serde_json::Value),
    Unrecognized5(Box<models::Unrecognized5>),
}

impl Default for SigningAlgorithmSpec {
    fn default() -> Self {
        Self::SigningAlgorithmSpecEcDsaSha256(Default::default())
    }
}

