/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SigningPublicKey {
    /// The serialization format of the public key  Required
    #[serde(rename = "format")]
    pub format: String,
    /// Serialized public key in the format specified above  Required: must be non-empty
    #[serde(rename = "keyData")]
    pub key_data: String,
    /// The key specification  Required
    #[serde(rename = "keySpec")]
    pub key_spec: String,
}

impl SigningPublicKey {
    pub fn new(format: String, key_data: String, key_spec: String) -> SigningPublicKey {
        SigningPublicKey {
            format,
            key_data,
            key_spec,
        }
    }
}

