/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum SignatureFormat {
    SignatureFormatConcat(serde_json::Value),
    SignatureFormatDer(serde_json::Value),
    SignatureFormatRaw(serde_json::Value),
    SignatureFormatSymbolic(serde_json::Value),
    SignatureFormatUnspecified(serde_json::Value),
    Unrecognized4(Box<models::Unrecognized4>),
}

impl Default for SignatureFormat {
    fn default() -> Self {
        Self::SignatureFormatConcat(Default::default())
    }
}

