/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Signature {
    /// Required
    #[serde(rename = "format")]
    pub format: String,
    /// Required: must be non-empty
    #[serde(rename = "signature")]
    pub signature: String,
    /// The fingerprint/id of the keypair used to create this signature and needed to verify.  Required
    #[serde(rename = "signedBy")]
    pub signed_by: String,
    /// The signing algorithm specification used to produce this signature  Required
    #[serde(rename = "signingAlgorithmSpec")]
    pub signing_algorithm_spec: String,
}

impl Signature {
    pub fn new(format: String, signature: String, signed_by: String, signing_algorithm_spec: String) -> Signature {
        Signature {
            format,
            signature,
            signed_by,
            signing_algorithm_spec,
        }
    }
}

