/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SubmitAndWaitForReassignmentRequest : This reassignment is executed as a single atomic update.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitAndWaitForReassignmentRequest {
    #[serde(rename = "reassignmentCommands")]
    pub reassignment_commands: Box<models::ReassignmentCommands>,
    #[serde(rename = "eventFormat", skip_serializing_if = "Option::is_none")]
    pub event_format: Option<Box<models::EventFormat>>,
}

impl SubmitAndWaitForReassignmentRequest {
    /// This reassignment is executed as a single atomic update.
    pub fn new(reassignment_commands: models::ReassignmentCommands) -> SubmitAndWaitForReassignmentRequest {
        SubmitAndWaitForReassignmentRequest {
            reassignment_commands: Box::new(reassignment_commands),
            event_format: None,
        }
    }
}

