/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SubmitAndWaitResponse {
    /// The id of the transaction that resulted from the submitted command. Must be a valid LedgerString (as described in ``value.proto``).  Required
    #[serde(rename = "updateId")]
    pub update_id: String,
    /// The details of the offset field are described in ``community/ledger-api/README.md``.  Required
    #[serde(rename = "completionOffset")]
    pub completion_offset: i64,
}

impl SubmitAndWaitResponse {
    pub fn new(update_id: String, completion_offset: i64) -> SubmitAndWaitResponse {
        SubmitAndWaitResponse {
            update_id,
            completion_offset,
        }
    }
}

