/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SynchronizerTime {
    /// The id of the synchronizer.  Required
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// All commands with a maximum record time below this value MUST be considered lost if their completion has not arrived before this checkpoint.  Required
    #[serde(rename = "recordTime")]
    pub record_time: String,
}

impl SynchronizerTime {
    pub fn new(synchronizer_id: String, record_time: String) -> SynchronizerTime {
        SynchronizerTime {
            synchronizer_id,
            record_time,
        }
    }
}

