/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeOneOf2 {
    #[serde(rename = "MinLedgerTimeRel")]
    pub min_ledger_time_rel: Box<models::MinLedgerTimeRel>,
}

impl TimeOneOf2 {
    pub fn new(min_ledger_time_rel: models::MinLedgerTimeRel) -> TimeOneOf2 {
        TimeOneOf2 {
            min_ledger_time_rel: Box::new(min_ledger_time_rel),
        }
    }
}

