/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TimeOneOf1 {
    #[serde(rename = "MinLedgerTimeAbs")]
    pub min_ledger_time_abs: Box<models::MinLedgerTimeAbs>,
}

impl TimeOneOf1 {
    pub fn new(min_ledger_time_abs: models::MinLedgerTimeAbs) -> TimeOneOf1 {
        TimeOneOf1 {
            min_ledger_time_abs: Box::new(min_ledger_time_abs),
        }
    }
}

