/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopologyStateFilter : Filter the vetted packages by the participant and synchronizer that they are hosted on.  Empty fields are ignored, such that a ``TopologyStateFilter`` without participant_ids and without synchronizer_ids matches a vetted package hosted on any participant and synchronizer.  Non-empty fields specify candidate values of which at least one must match. If both fields are set then at least one candidate value must match from each field.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopologyStateFilter {
    /// If this list is non-empty, only vetted packages hosted on participants listed in this field match the filter. Query the current Ledger API's participant's ID via the public ``GetParticipantId`` command in ``PartyManagementService``.  Optional: can be empty
    #[serde(rename = "participantIds", skip_serializing_if = "Option::is_none")]
    pub participant_ids: Option<Vec<String>>,
    /// If this list is non-empty, only vetted packages from the topology state of the synchronizers in this list match the filter.  Optional: can be empty
    #[serde(rename = "synchronizerIds", skip_serializing_if = "Option::is_none")]
    pub synchronizer_ids: Option<Vec<String>>,
}

impl TopologyStateFilter {
    /// Filter the vetted packages by the participant and synchronizer that they are hosted on.  Empty fields are ignored, such that a ``TopologyStateFilter`` without participant_ids and without synchronizer_ids matches a vetted package hosted on any participant and synchronizer.  Non-empty fields specify candidate values of which at least one must match. If both fields are set then at least one candidate value must match from each field.
    pub fn new() -> TopologyStateFilter {
        TopologyStateFilter {
            participant_ids: None,
            synchronizer_ids: None,
        }
    }
}

