/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TopologyFormat : A format specifying which topology transactions to include and how to render them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TopologyFormat {
    #[serde(rename = "includeParticipantAuthorizationEvents", skip_serializing_if = "Option::is_none")]
    pub include_participant_authorization_events: Option<Box<models::ParticipantAuthorizationTopologyFormat>>,
}

impl TopologyFormat {
    /// A format specifying which topology transactions to include and how to render them.
    pub fn new() -> TopologyFormat {
        TopologyFormat {
            include_participant_authorization_events: None,
        }
    }
}

