/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionFilter : Provided for backwards compatibility, it will be removed in the Canton version 3.4.0. Used both for filtering create and archive events as well as for filtering transaction trees.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionFilter {
    #[serde(rename = "filtersByParty")]
    pub filters_by_party: std::collections::HashMap<String, models::Filters>,
    #[serde(rename = "filtersForAnyParty", skip_serializing_if = "Option::is_none")]
    pub filters_for_any_party: Option<Box<models::Filters>>,
}

impl TransactionFilter {
    /// Provided for backwards compatibility, it will be removed in the Canton version 3.4.0. Used both for filtering create and archive events as well as for filtering transaction trees.
    pub fn new(filters_by_party: std::collections::HashMap<String, models::Filters>) -> TransactionFilter {
        TransactionFilter {
            filters_by_party,
            filters_for_any_party: None,
        }
    }
}

