/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionFormat : A format that specifies what events to include in Daml transactions and what data to compute and include for them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionFormat {
    #[serde(rename = "eventFormat", skip_serializing_if = "Option::is_none")]
    pub event_format: Option<Box<models::EventFormat>>,
    #[serde(rename = "transactionShape")]
    pub transaction_shape: Box<models::TransactionShape>,
}

impl TransactionFormat {
    /// A format that specifies what events to include in Daml transactions and what data to compute and include for them.
    pub fn new(transaction_shape: models::TransactionShape) -> TransactionFormat {
        TransactionFormat {
            event_format: None,
            transaction_shape: Box::new(transaction_shape),
        }
    }
}

