/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TransactionFilter : Deprecated: disabled unless `canton.participants.<participant>.features.deprecated.enable-deprecated-parameters-34 = true`; it will be removed in the Canton version 3.7.0. Used both for filtering create and archive events as well as for filtering transaction trees.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct TransactionFilter {
    #[serde(rename = "filtersByParty", skip_serializing_if = "Option::is_none")]
    pub filters_by_party: Option<std::collections::HashMap<String, models::Filters>>,
    #[serde(rename = "filtersForAnyParty", skip_serializing_if = "Option::is_none")]
    pub filters_for_any_party: Option<Box<models::Filters>>,
}

impl TransactionFilter {
    /// Deprecated: disabled unless `canton.participants.<participant>.features.deprecated.enable-deprecated-parameters-34 = true`; it will be removed in the Canton version 3.7.0. Used both for filtering create and archive events as well as for filtering transaction trees.
    pub fn new() -> TransactionFilter {
        TransactionFilter {
            filters_by_party: None,
            filters_for_any_party: None,
        }
    }
}

