/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Transaction : Filtered view of an on-ledger transaction's create and archive events.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Transaction {
    #[serde(rename = "value")]
    pub value: Box<models::JsTransaction>,
}

impl Transaction {
    /// Filtered view of an on-ledger transaction's create and archive events.
    pub fn new(value: models::JsTransaction) -> Transaction {
        Transaction {
            value: Box::new(value),
        }
    }
}

