/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// TreeEvent : Provided for backwards compatibility, it will be removed in the Canton version 3.5.0. Each tree event message type below contains a ``witness_parties`` field which indicates the subset of the requested parties that can see the event in question.  Note that transaction trees might contain events with _no_ witness parties, which were included simply because they were children of events which have witnesses.
/// Provided for backwards compatibility, it will be removed in the Canton version 3.5.0. Each tree event message type below contains a ``witness_parties`` field which indicates the subset of the requested parties that can see the event in question.  Note that transaction trees might contain events with _no_ witness parties, which were included simply because they were children of events which have witnesses.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum TreeEvent {
    TreeEventOneOf(Box<models::TreeEventOneOf>),
    TreeEventOneOf1(Box<models::TreeEventOneOf1>),
}

impl Default for TreeEvent {
    fn default() -> Self {
        Self::TreeEventOneOf(Default::default())
    }
}

