/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnassignCommand1 : Unassign a contract
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnassignCommand1 {
    /// The ID of the contract the client wants to unassign. Must be a valid LedgerString (as described in ``value.proto``).  Required
    #[serde(rename = "contractId")]
    pub contract_id: String,
    /// The ID of the source synchronizer Must be a valid synchronizer id  Required
    #[serde(rename = "source")]
    pub source: String,
    /// The ID of the target synchronizer Must be a valid synchronizer id  Required
    #[serde(rename = "target")]
    pub target: String,
}

impl UnassignCommand1 {
    /// Unassign a contract
    pub fn new(contract_id: String, source: String, target: String) -> UnassignCommand1 {
        UnassignCommand1 {
            contract_id,
            source,
            target,
        }
    }
}

