/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnassignCommand : Unassign a contract
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnassignCommand {
    #[serde(rename = "value")]
    pub value: Box<models::UnassignCommand1>,
}

impl UnassignCommand {
    /// Unassign a contract
    pub fn new(value: models::UnassignCommand1) -> UnassignCommand {
        UnassignCommand {
            value: Box::new(value),
        }
    }
}

