/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UnassignCommand1 : Unassign a contract
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UnassignCommand1 {
    /// The ID of the contract the client wants to unassign. Must be a valid LedgerString (as described in ``value.proto``). Required
    #[serde(rename = "contractId")]
    pub contract_id: String,
    /// The ID of the source synchronizer Must be a valid synchronizer id Required
    #[serde(rename = "source")]
    pub source: String,
    /// The ID of the target synchronizer Must be a valid synchronizer id Required
    #[serde(rename = "target")]
    pub target: String,
}

impl UnassignCommand1 {
    /// Unassign a contract
    pub fn new(contract_id: String, source: String, target: String) -> UnassignCommand1 {
        UnassignCommand1 {
            contract_id,
            source,
            target,
        }
    }
}

