/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Unrecognized2 {
    #[serde(rename = "unrecognizedValue")]
    pub unrecognized_value: i32,
}

impl Unrecognized2 {
    pub fn new(unrecognized_value: i32) -> Unrecognized2 {
        Unrecognized2 {
            unrecognized_value,
        }
    }
}

