/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Unvet1 : Remove packages from the set of vetted packages
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Unvet1 {
    /// Packages to be unvetted.  If a reference in this list matches multiple packages, they are all unvetted.  Required: must be non-empty
    #[serde(rename = "packages")]
    pub packages: Vec<models::VettedPackagesRef>,
}

impl Unvet1 {
    /// Remove packages from the set of vetted packages
    pub fn new(packages: Vec<models::VettedPackagesRef>) -> Unvet1 {
        Unvet1 {
            packages,
        }
    }
}

