/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateFormat : A format specifying what updates to include and how to render them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFormat {
    #[serde(rename = "includeTransactions", skip_serializing_if = "Option::is_none")]
    pub include_transactions: Option<Box<models::TransactionFormat>>,
    #[serde(rename = "includeReassignments", skip_serializing_if = "Option::is_none")]
    pub include_reassignments: Option<Box<models::EventFormat>>,
    #[serde(rename = "includeTopologyEvents", skip_serializing_if = "Option::is_none")]
    pub include_topology_events: Option<Box<models::TopologyFormat>>,
}

impl UpdateFormat {
    /// A format specifying what updates to include and how to render them.
    pub fn new() -> UpdateFormat {
        UpdateFormat {
            include_transactions: None,
            include_reassignments: None,
            include_topology_events: None,
        }
    }
}

