/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateFormat : A format specifying what updates to include and how to render them.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateFormat {
    #[serde(rename = "includeTransactions", skip_serializing_if = "Option::is_none")]
    pub include_transactions: Option<Box<models::TransactionFormat>>,
    #[serde(rename = "includeReassignments", skip_serializing_if = "Option::is_none")]
    pub include_reassignments: Option<Box<models::EventFormat>>,
    #[serde(rename = "includeTopologyEvents", skip_serializing_if = "Option::is_none")]
    pub include_topology_events: Option<Box<models::TopologyFormat>>,
}

impl UpdateFormat {
    /// A format specifying what updates to include and how to render them.
    pub fn new() -> UpdateFormat {
        UpdateFormat {
            include_transactions: None,
            include_reassignments: None,
            include_topology_events: None,
        }
    }
}

