/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateVettedPackagesResponse {
    #[serde(rename = "pastVettedPackages", skip_serializing_if = "Option::is_none")]
    pub past_vetted_packages: Option<Box<models::VettedPackages>>,
    #[serde(rename = "newVettedPackages")]
    pub new_vetted_packages: Box<models::VettedPackages>,
}

impl UpdateVettedPackagesResponse {
    pub fn new(new_vetted_packages: models::VettedPackages) -> UpdateVettedPackagesResponse {
        UpdateVettedPackagesResponse {
            past_vetted_packages: None,
            new_vetted_packages: Box::new(new_vetted_packages),
        }
    }
}

