/*
 * JSON Ledger API HTTP endpoints
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 3.3.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Update1OneOf2 {
    #[serde(rename = "TransactionTree")]
    pub transaction_tree: Box<models::TransactionTree>,
}

impl Update1OneOf2 {
    pub fn new(transaction_tree: models::TransactionTree) -> Update1OneOf2 {
        Update1OneOf2 {
            transaction_tree: Box::new(transaction_tree),
        }
    }
}

