/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateAccountRequest {
    /// The account ID whose account to update.  NOTE: Currently, the account ID is tied to and identified by a party ID. This constraint is expected to be removed in a future release, allowing for user-defined account IDs that are not necessarily tied to a specific party.  Required
    #[serde(rename = "accountId")]
    pub account_id: String,
    /// Balance DELTA to apply to the current balance. Negative values will decrease the balance, positive values will increase the balance. If unset, the balance will not be updated  Note that setting a negative value may result in a negative balance if the delta is larger than the current balance. Optional
    #[serde(rename = "balanceDelta", skip_serializing_if = "Option::is_none")]
    pub balance_delta: Option<i64>,
    /// Identifier of this logical update, used to de-duplicate. The caller MUST use a distinct id for every distinct update, and MUST reuse the same id when retrying an update that failed after a retryable error. An already processed id is ignored, while a fresh id applies the delta again.  Required
    #[serde(rename = "deduplicationId")]
    pub deduplication_id: String,
}

impl UpdateAccountRequest {
    pub fn new(account_id: String, deduplication_id: String) -> UpdateAccountRequest {
        UpdateAccountRequest {
            account_id,
            balance_delta: None,
            deduplication_id,
        }
    }
}

