/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// UpdateUserIdentityProviderIdRequest : Required authorization: ``HasRight(ParticipantAdmin)``
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateUserIdentityProviderIdRequest {
    /// User to update  Required
    #[serde(rename = "userId")]
    pub user_id: String,
    /// Current identity provider ID of the user If omitted, the default IDP is assumed  Optional
    #[serde(rename = "sourceIdentityProviderId", skip_serializing_if = "Option::is_none")]
    pub source_identity_provider_id: Option<String>,
    /// Target identity provider ID of the user If omitted, the default IDP is assumed  Optional
    #[serde(rename = "targetIdentityProviderId", skip_serializing_if = "Option::is_none")]
    pub target_identity_provider_id: Option<String>,
}

impl UpdateUserIdentityProviderIdRequest {
    /// Required authorization: ``HasRight(ParticipantAdmin)``
    pub fn new(user_id: String) -> UpdateUserIdentityProviderIdRequest {
        UpdateUserIdentityProviderIdRequest {
            user_id,
            source_identity_provider_id: None,
            target_identity_provider_id: None,
        }
    }
}

