/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification from the previous Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.4.12
 *
 * The version of the OpenAPI document: 3.4.12-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vet1 {
    #[serde(rename = "packages", skip_serializing_if = "Option::is_none")]
    pub packages: Option<Vec<models::VettedPackagesRef>>,
    #[serde(rename = "newValidFromInclusive", skip_serializing_if = "Option::is_none")]
    pub new_valid_from_inclusive: Option<String>,
    #[serde(rename = "newValidUntilExclusive", skip_serializing_if = "Option::is_none")]
    pub new_valid_until_exclusive: Option<String>,
}

impl Vet1 {
    pub fn new() -> Vet1 {
        Vet1 {
            packages: None,
            new_valid_from_inclusive: None,
            new_valid_until_exclusive: None,
        }
    }
}

