/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.1
 *
 * The version of the OpenAPI document: 3.6.1
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Vet1 : Set vetting bounds of a list of packages. Packages that were not previously vetted have their bounds added, previous vetting bounds are overwritten.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Vet1 {
    /// Packages to be vetted.  If a reference in this list matches more than one package, the change is considered ambiguous and the entire update request is rejected. In other words, every reference must match exactly one package.  Required: must be non-empty
    #[serde(rename = "packages")]
    pub packages: Vec<models::VettedPackagesRef>,
    /// The time from which these packages should be vetted, prior lower bounds are overwritten. Optional
    #[serde(rename = "newValidFromInclusive", skip_serializing_if = "Option::is_none")]
    pub new_valid_from_inclusive: Option<String>,
    /// The time until which these packages should be vetted, prior upper bounds are overwritten. Optional
    #[serde(rename = "newValidUntilExclusive", skip_serializing_if = "Option::is_none")]
    pub new_valid_until_exclusive: Option<String>,
}

impl Vet1 {
    /// Set vetting bounds of a list of packages. Packages that were not previously vetted have their bounds added, previous vetting bounds are overwritten.
    pub fn new(packages: Vec<models::VettedPackagesRef>) -> Vet1 {
        Vet1 {
            packages,
            new_valid_from_inclusive: None,
            new_valid_until_exclusive: None,
        }
    }
}

