/*
 * JSON Ledger API HTTP endpoints
 *
 * This specification version fixes the API inconsistencies where certain fields marked as required in the spec are in fact optional. If you use code generation tool based on this file, you might need to adjust the existing application code to handle those fields as optional. If you do not want to change your client code, continue using the OpenAPI specification for the latest Canton 3.4 patch release. MINIMUM_CANTON_VERSION=3.6.0
 *
 * The version of the OpenAPI document: 3.6.0-SNAPSHOT
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VettedPackages : The list of packages vetted on a given participant and synchronizer, modelled after ``VettedPackages`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_. The list only contains packages that matched a filter in the query that originated it.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VettedPackages {
    /// Sorted by package_name and package_version where known, and package_id as a last resort.  Required: must be non-empty
    #[serde(rename = "packages")]
    pub packages: Vec<models::VettedPackage>,
    /// Participant on which these packages are vetted.  Required
    #[serde(rename = "participantId")]
    pub participant_id: String,
    /// Synchronizer on which these packages are vetted.  Required
    #[serde(rename = "synchronizerId")]
    pub synchronizer_id: String,
    /// Serial of last ``VettedPackages`` topology transaction of this participant and on this synchronizer.  Required
    #[serde(rename = "topologySerial")]
    pub topology_serial: i32,
}

impl VettedPackages {
    /// The list of packages vetted on a given participant and synchronizer, modelled after ``VettedPackages`` in `topology.proto <https://github.com/digital-asset/canton/blob/main/community/base/src/main/protobuf/com/digitalasset/canton/protocol/v30/topology.proto#L206>`_. The list only contains packages that matched a filter in the query that originated it.
    pub fn new(packages: Vec<models::VettedPackage>, participant_id: String, synchronizer_id: String, topology_serial: i32) -> VettedPackages {
        VettedPackages {
            packages,
            participant_id,
            synchronizer_id,
            topology_serial,
        }
    }
}

